Repository 1024pix/pix-editor, pull requests merged in 2021-06, with the labels that each got.

#190 [TECH] Ajout du linter eslint-plugin-qunit
  pix-editor/.eslintrc.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/competence/prototypes/list-test.js
  pix-editor/tests/acceptance/create-framework-test.js
  pix-editor/tests/acceptance/login-test.js
  pix-editor/tests/integration/components/field/toggle-field-test.js
  pix-editor/tests/integration/components/pop-in/changelog-test.js
  pix-editor/tests/integration/components/pop-in/login-form-test.js
  pix-editor/tests/integration/components/pop-in/logout-test.js
  pix-editor/tests/integration/components/pop-in/select-location-test.js
  pix-editor/tests/integration/components/pop-in/sorting-test.js
  pix-editor/tests/integration/components/pop-in/tube-level-test.js
  pix-editor/tests/integration/components/pop-in/tutorial-test.js
  pix-editor/tests/integration/components/sidebar/navigation-test.js
  pix-editor/tests/unit/controllers/competence-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
  pix-editor/tests/unit/controllers/target-profile-test.js
  pix-editor/tests/unit/models/theme-test.js
  pix-editor/tests/unit/models/tube-test.js
  pix-editor/tests/unit/services/access-test.js
  pix-editor/tests/unit/services/changelog-entry-test.js
  pix-editor/tests/unit/services/storage-test.js
Labels: :rocket: Ready to Merge

#189 [TECH] Vérification des droits sur les routes API.
  api/lib/application/airtable-proxy.js
  api/lib/application/file-storage-token/index.js
  api/lib/application/releases.js
  api/lib/application/security-pre-handlers.js
  api/tests/acceptance/application/airtable-proxy-controller-changelog_test.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/airtable-proxy-controller_test.js
  api/tests/acceptance/application/config/config-controller_test.js
  api/tests/acceptance/application/file-storage-token_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/users_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-ref

#188 [TECH] Utilise la table `attachments` dans les formulaires de Pix Editor.
  pix-editor/app/components/field/files.hbs
  pix-editor/app/components/field/files.js
  pix-editor/app/components/field/illustration.hbs
  pix-editor/app/components/field/illustration.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/controllers/competence/prototypes/new.js
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/app/models/challenge.js
  pix-editor/app/routes/competence/prototypes/single.js
  pix-editor/app/serializers/challenge.js
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/challenge.js
  pix-editor/tests/acceptance/create-challenge-alternative-test.js
  pix-editor/tests/unit/component/field/illustration-test.js
  pix-editor/tests/unit/component/form/challenge-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
  pix-editor/tests/unit/serializers/challenge-test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed

#186 [FEATURE] Ajouter les thématiques à l'export des sujet (PE-64)
  pix-editor/app/components/sidebar/export.js
  pix-editor/tests/unit/component/sidebar/export-test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-ref

#191 [BUGFIX] N'essaye pas d'ouvrir airtable ou la preview toujours dans la même fenêtre
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/app/controllers/competence/skills/single.js
  pix-editor/app/controllers/competence/tubes/single.js
  pix-editor/app/templates/competence/prototypes/single.hbs
  pix-editor/app/templates/competence/skills/single.hbs
  pix-editor/app/templates/competence/tubes/single.hbs
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-ref
