Repository 1024pix/pix-editor, pull requests merged in 2021-07, with the labels that each got.

#192 [TECH] Nettoyage d'attribut et de l'utilisation de nock.cleanAll
  api/tests/acceptance/application/airtable-proxy-controller-changelog_test.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/airtable-proxy-controller_test.js
  api/tests/test-helper.js
  api/tests/unit/infrastructure/event-notifier/updated-record-notifier_test.js
  api/tests/unit/infrastructure/pix-api-client_test.js
  pix-editor/app/models/challenge.js
  pix-editor/mirage/factories/challenge.js
Labels: :rocket: Ready to Merge, Tech Review Needed

#193 [TECH] Mise à jour des dépendances "vulnérable"
  api/package-lock.json
  scripts/package-lock.json
Labels: :rocket: Ready to Merge, Tech Review Needed, team-ref

#194 [BUGFIX] Supprime un caractère non voulu dans le message de nouvelle version
  pix-editor/app/controllers/competence/prototypes/new.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-ref

#195 [TECH] Utilise une base de données spécifique pour redis en mode test
  api/lib/config.js
Labels: :rocket: Ready to Merge, Tech Review Needed, team-ref

#185 [TECH] Utilise le format JSON:API pour la communication entre pix editor et l'api LCMS pour la manipulation des Epreuves.
  api/lib/application/challenges/index.js
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/config-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/unit/infrastructure/airtable/datasources/challenge-datasource_test.js
  api/tests/unit/infrastructure/airtable/datasources/datasource_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/adapters/challenge.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/components/sidebar/search.js
  pix-editor/app/models/challenge.js
  pix-editor/app/models/config.js
  pix-editor/app/serializers/challenge.js
  pix-editor/app/services/config.js
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/challenge.js
  pix-editor/tests/acceptance/search-test.js
  pix-editor/tests/unit/component/form/challenge-test.js
  pix-editor/tests/unit/models/challenge-test.js
  pix-editor/tests/unit/serializers/challenge-test.js
Labels: :rocket: Ready to Merge, Func Review Needed, Tech Review Needed, team-ref
