Repository 1024pix/pix-editor, pull requests merged in 2022-08, with the labels that each got.

#57 [FEATURE] Ajouter les formations à la release (PIX-5436).
  api/lib/domain/models/Content.js
  api/lib/domain/models/Training.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/training-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: :rocket: Ready to Merge, team-evaluation, Tech Review OK

#58 [TECH] Utilise l'automerge 1024pix.
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge, team-contenu

#59 [CLEANUP] Correction du badge circleci dans le readme
  README.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#55 [TECH] Mettre à jour AdminBro vers AdminJS (PIX-5433).
  .gitignore
  api/adminjs/components/list.duration.component.jsx
  api/adminjs/components/show.duration.component.jsx
  api/adminjs/components/use-interval.js
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
