Repository 1024pix/pix-editor, pull requests merged in 2022-09, with the labels that each got.

#61 [CLEANUP] Met à jour l'action d'auto merge commune
  .github/workflows/auto-merge.yml
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#62 [BUGFIX] Corrige l'enrichissement des logs de requêtes
  api/lib/infrastructure/monitoring-tools.js
  api/lib/infrastructure/plugins/adminjs.js
  api/lib/infrastructure/plugins/index.js
  api/lib/infrastructure/plugins/pino.js
  api/lib/infrastructure/plugins/sentry.js
  api/lib/plugins.js
  api/package-lock.json
  api/package.json
  api/server.js
  api/tests/integration/infrastructure/plugins/pino_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#63 [FEATURE] Ajout d'un nouveau rôle pour limiter l’accès au référentiel pix (PIX-5618).
  api/.adminbro/.entry.js
  api/db/migrations/20220906082935_add-read-pix-only-role.js
  api/db/seeds/seed.js
  api/package.json
  pix-editor/app/components/sidebar/navigation.hbs
  pix-editor/app/components/sidebar/navigation.js
  pix-editor/app/services/access.js
  pix-editor/tests/acceptance/navigate-through-frameworks-test.js
  pix-editor/tests/integration/components/sidebar/navigation-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#65 [FEATURE] Ne pas afficher le générateur de profile cible pour les utilisateur `READ_PIX_ONLY` (PIX-5671).
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/components/sidebar/navigation.hbs
  pix-editor/app/components/sidebar/navigation.js
  pix-editor/tests/acceptance/navigate-through-frameworks-test.js
  pix-editor/tests/integration/components/sidebar/navigation-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#66 [TECH] Mise a jour caniuse-lite (PIX-5719).
  pix-editor/package-lock.json
Labels: :rocket: Ready to Merge
