Repository 1024pix/pix-editor, pull requests merged in 2022-10, with the labels that each got.

#67 [FEATURE] Ne pas afficher le champ de recherche pour les utilisateurs `READ_PIX_ONLY` (PIX-5819).
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/components/sidebar/navigation.hbs
  pix-editor/app/components/sidebar/search.hbs
  pix-editor/tests/acceptance/navigate-through-frameworks-test.js
  pix-editor/tests/integration/components/sidebar/navigation-test.js
  pix-editor/tests/integration/components/sidebar/search-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#68 [TECH] Suppression des formations (PIX-5777)
  api/.adminbro/.entry.js
  api/adminjs/components/list.duration.component.jsx
  api/adminjs/components/show.duration.component.jsx
  api/adminjs/components/use-interval.js
  api/db/migrations/20221011133651_delete-trainings.js
  api/db/seeds/seed.js
  api/lib/domain/models/Content.js
  api/lib/domain/models/Training.js
  api/lib/infrastructure/plugins/adminjs.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/training-repository.js
  api/lib/models/index.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/training-repository_test.js
  api/tests/tooling/database-builder/factory/build-training.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/repositories/release-repository_test.js
Labels: :rocket: Ready to Merge, team-evaluation, Tech Review OK

#70 [BUGFIX] Améliorer le libellé indiquant la présence d'une alternative textuelle sur les illustrations dans une épreuve
  pix-editor/app/components/form/challenge.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, team-evaluation, Tech Review OK
