Repository 1024pix/pix-editor, pull requests merged in 2022-12, with the labels that each got.

#75 [TECH] Mettre a jour le port utiliser par la base de donnée dans les variables d'environnement.
  api/sample.env
  end-to-end-tests/package.json
Labels: :rocket: Ready to Merge, Tech Review OK

#80 [TECH] Ne plus ajouter de lien vers la review-app dans la pull-request
  package.json
  scripts/signal_deploy_to_pr.sh
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#79 [TECH] Tracer facilement les métriques infra
  api/lib/config.js
  api/lib/infrastructure/validate-environement-variables.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/server.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#76 [TECH] Mettre à jour les paquets non problématiques de Pix Editor (PIX-6461).
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review Needed
