Repository 1024pix/pix-editor, pull requests merged in 2022-02, with the labels that each got.

#29 [TECH] Exposer la relation Skill -> Challenge sous forme de 1 -> N plutot que N <-> N
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#26 [FEATURE] Permettre l'extraction de la liste des sujet en anglais (PIX-4156).
  pix-editor/app/components/pop-in/pdf-entries.hbs
  pix-editor/app/components/pop-in/pdf-entries.js
  pix-editor/app/components/target-profile/pdf-export.hbs
  pix-editor/app/components/target-profile/pdf-export.js
  pix-editor/app/styles/_global.scss
  pix-editor/tests/integration/components/pop-in/pdf-entries-test.js
  pix-editor/tests/unit/component/target-profile/pdf-export-test.js
  pix-editor/translations/fr.yaml
Labels: :rocket: Ready to Merge, team-contenu

#9 [BUG FIX] Archiver ou rendre obsolète un prototype actif crée un soucis dans la gestion du statut de son acquis (PIX 4064)
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
Labels: :rocket: Ready to Merge, team-contenu

#28 [FEATURE] Expose les différentiels référentiels dans la release
  api/lib/domain/models/Area.js
  api/lib/domain/models/Content.js
  api/lib/domain/models/Framework.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/datasources/airtable/framework-datasource.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/airtable-builder/airtable-builder.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/airtable-builder/factory/build-framework.js
  api/tests/tooling/airtable-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-area-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-framework.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/datasources/airtable/framwork-datasource_test.js
  api/tests/unit/infrastructure/serializers/airtable-serializer_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#31 [FEATURE] Modification de la popin de changelog lors de la modification
  end-to-end-tests/cypress/integration/modify-challenge.spec.js
  pix-editor/app/components/pop-in/confirm-log.hbs
  pix-editor/app/components/pop-in/confirm-log.js
  pix-editor/app/components/pop-in/pdf-entries.hbs
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/app/controllers/competence/prototypes/single/alternatives/single.js
  pix-editor/app/controllers/competence/skills/single.js
  pix-editor/app/styles/_confirm-log.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/templates/competence/prototypes/single.hbs
  pix-editor/app/templates/competence/skills/single.hbs
  pix-editor/tests/acceptance/create-challenge-alternative-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-attachment-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-illustration-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/integration/components/pop-in/confirm-log-test.js
  pix-editor/tests/setup-intl-rendering.js
  pix-editor/tests/setup-intl.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
  pix-editor/translations/fr.yaml
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#32 [BUGFIX] Le titre de la popIn qui s'affiche lors de la modification d'un acquis ne possède pas de traduction (PIX-4352).
  pix-editor/app/templates/competence/skills/single.hbs
Labels: :rocket: Ready to Merge, team-contenu

#33 [BUGFIX] Le titre du bouton valider lorsqu'on met en production une épreuve en "proposée" ne possède pas de traduction.
  pix-editor/app/templates/competence/prototypes/single.hbs
Labels: :rocket: Ready to Merge

#34 [TECH] Renommer la clé d'api admin
  INSTALL.md
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#35 [FEATURE] Ajouter une vue 'en construction' pour la section acquis (PIX-3588).
  pix-editor/app/components/competence/competence-actions.hbs
  pix-editor/app/components/competence/competence-grid-tube.hbs
  pix-editor/app/components/competence/competence-header.hbs
  pix-editor/app/components/competence/competence-header.js
  pix-editor/app/components/competence/grid/grid-cell.hbs
  pix-editor/app/components/competence/grid/grid-cell.js
  pix-editor/app/models/tube.js
  pix-editor/app/routes/competence/skills/index.js
  pix-editor/app/routes/competence/skills/single.js
  pix-editor/tests/integration/components/competence/competence-actions-test.js
  pix-editor/tests/unit/component/grid/grid-cell_test.js
  pix-editor/tests/unit/models/tube-test.js
Labels: :rocket: Ready to Merge, team-contenu

#37 [CLEANUP] Modifie la relation challenge -> skill en 1 -> 1 (PIX-4290)
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/components/pop-in/challenge-log.hbs
  pix-editor/app/controllers/competence/prototypes/new.js
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/app/controllers/competence/prototypes/single/alternatives/new.js
  pix-editor/app/models/challenge.js
  pix-editor/app/routes/challenge.js
  pix-editor/app/routes/competence.js
  pix-editor/app/routes/competence/prototypes/new.js
  pix-editor/app/routes/competence/prototypes/single.js
  pix-editor/app/templates/competence/prototypes/single.hbs
  pix-editor/app/templates/competence/prototypes/single/alternatives.hbs
  pix-editor/app/templates/competence/skills/list.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/prototypes/list-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-attachment-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-illustration-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/integration/components/pop-in/select-location-test.js
  pix-editor/tests/unit/models/challenge-test.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#36 [TECH] Corriger le nom des fichiers des pièces jointes au moment de la création d'une épreuve (PIX-4018)
  pix-editor/app/services/storage.js
Labels: :rocket: Ready to Merge

#39 [FEATURE] Pouvoir modifier une épreuve archivée depuis pix editor (PIX-442).
  pix-editor/app/services/access.js
  pix-editor/tests/unit/services/access-test.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed
