Repository 1024pix/pix-editor, pull requests merged in 2022-01, with the labels that each got.

#11 [TECH] Ajout du numéro de job dans les logs
  api/lib/infrastructure/scheduled-jobs/create-queue.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#12 [TECH] Utilise notre propre vérificateur d'URLs en erreur
  .eslintrc.yaml
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/repositories/url-error-repository.js
  api/lib/infrastructure/scheduled-jobs/check-urls-job.js
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#14 [FEATURE] Met à jour le wording de mise en obsolescence des acquis (PIX-4092)
  pix-editor/app/components/competence/grid/cell-skill-workbench.hbs
  pix-editor/app/components/competence/grid/cell-skill-workbench.js
  pix-editor/app/components/competence/grid/cell-workbench.hbs
  pix-editor/app/components/competence/grid/cell-workbench.js
  pix-editor/app/controllers/competence/prototypes/single.js
  pix-editor/app/controllers/competence/skills/single.js
  pix-editor/app/models/challenge.js
  pix-editor/app/models/skill.js
  pix-editor/app/services/access.js
  pix-editor/app/styles/_competence.scss
  pix-editor/app/templates/competence/prototypes/single.hbs
  pix-editor/app/templates/competence/skills/single.hbs
  pix-editor/tests/integration/components/competence/grid/cell-skill-workbench-test.js
  pix-editor/tests/integration/components/competence/grid/cell-workbench-test.js
  pix-editor/tests/unit/services/access-test.js
  pix-editor/translations/fr.yaml
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#15 [CLEANUP] Supprime la gestion des status pré-validé et validé sans test des épreuves (PIX-4126)
  pix-editor/app/models/challenge.js
  scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
  scripts/copy-skills-and-set-challenges-as-focusable/index.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#16 [FEATURE] Ajout de contexte sur l'extract des URLs du référentiel (PIX-4154)
  api/scripts/get-external-urls-list/index.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#17 [BUGFIX] Corrige la concurrence de vérifications des URLs
  api/lib/domain/usecases/validate-urls-from-release.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#18 |BUGFIX] Corrige certaines urls injustement marqué comme invalides
  api/lib/domain/usecases/validate-urls-from-release.js
  api/package-lock.json
  api/package.json
  api/scripts/check-url.js
Labels: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#20 [TECH] Ajouter le champ responsive d'une épreuve a la release du référentiel (PIX-4202).
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
Labels: :rocket: Ready to Merge

#22 [CLEANUP] Corrige le chemin des tests unitaires des datasources
  api/tests/unit/infrastructure/datasources/airtable/area-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/attachment-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/competence-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/thematic-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/tube-datasource_test.js
  api/tests/unit/infrastructure/datasources/airtable/tutorial-datasource_test.js
Labels: :rocket: Ready to Merge

#24 [TECH] Ajout de la généalogie d'une épreuve (PIX-4271).
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
Labels: :rocket: Ready to Merge, team-contenu

#23 [FEATURE] Affichage du nom des thématiques en anglais (PIX-4258)
  pix-editor/app/components/form/theme.hbs
  pix-editor/app/models/theme.js
  pix-editor/app/serializers/theme.js
  pix-editor/mirage/factories/theme.js
  pix-editor/tests/integration/components/form/theme-test.js
Labels: :rocket: Ready to Merge, team-contenu
