Repository 1024pix/pix-editor, pull requests merged in 2023-11, with the labels that each got.

#372 [TECH] Utilise la version officielle de @adminjs/hapijs.
  api/lib/infrastructure/plugins/adminjs/index.js
  api/package-lock.json
  api/package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#370 [FEATURE] Ecrire dans PG les traductions des Acquis (PIX-9399)
  api/lib/application/airtable-proxy.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/translations/index.js
  api/lib/infrastructure/translations/skill.js
  api/scripts/migrate-skills-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy-controller-skill_test.js
  api/tests/scripts/migrate-skills-translation-from-airtable_test.js
  api/tests/tooling/input-output-data-builder/factory/build-skill.js
  api/tests/tooling/input-output-data-builder/factory/index.js
  api/tests/unit/infrastructure/translations/skill_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#377 [BUGFIX] Les traductions des acquis sont lues depuis PG avant que la table soit remplie
  api/lib/application/airtable-proxy.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#371 [FEATURE] Lire les traductions des acquis côté front (PIX-9401)
  api/lib/application/airtable-proxy.js
  api/tests/acceptance/application/airtable-proxy-controller-skill_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#382 [TECH] Migre les scripts vers ESModules.
  scripts/.eslintrc.yaml
  scripts/common/read-json-file.js
  scripts/common/token.js
  scripts/compare-challenges-and-attachments/index-tests.js
  scripts/compare-challenges-and-attachments/index.js
  scripts/compare-releases-integrity/index-tests.js
  scripts/compare-releases-integrity/index.js
  scripts/copy-skills-and-set-challenges-as-focusable/airtable-fields.js
  scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
  scripts/copy-skills-and-set-challenges-as-focusable/index.js
  scripts/enable-shuffled-on-challenges/index.js
  scripts/migrate-attachments-from-airtable/index-tests.js
  scripts/migrate-attachments-from-airtable/index.js
  scripts/migrate-attachments-in-subfolder/index-tests.js
  scripts/migrate-attachments-in-subfolder/index.js
  scripts/migrate-static-courses-from-airtable/index.js
  scripts/package.json
  scripts/populate-alpha-and-delta-column-with-csv/index-tests.js
  scripts/populate-alpha-and-delta-column-with-csv/index.js
  scripts/populate-alpha-and-delta-column/index-tests.js
  scripts/populate-alpha-and-delta-column/index.js
  scripts/restore-challenges-validated-and-archived-at/index.js
  scripts/reverse-static-courses-challenges-order/index.js
  scripts/set-headers-to-attachments/index-tests.js
  scripts/set-headers-to-attachments/index.js
Labels: :rocket: Ready to Merge, Tech Review OK

#383 [TECH] Mettre à jour playwright.
  .circleci/config.yml
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#375 [TECH] Mutualiser les outils de traduction dans translation utils (PIX-10083)
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/skill.js
  api/lib/infrastructure/translations/utils.js
  api/tests/unit/infrastructure/translations/competence_test.js
  api/tests/unit/infrastructure/translations/skill_test.js
  api/tests/unit/infrastructure/translations/utils_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#378 [FEATURE] Ajouter les épreuves localisées dans la release (PIX-10017).
  api/db/migrations/20231120095724_create-localized-challenges-table.js
  api/db/seeds/data/localized-challenges.js
  api/db/seeds/seed.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/index.js
  api/lib/domain/services/convert-locales.js
  api/lib/domain/usecases/import-translations.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/lib/infrastructure/translations/challenge.js
  api/scripts/fill-localized-challenges/index.js
  api/scripts/migrate-challenges-translation-from-airtable/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/scripts/fill-localized-challenges_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/database-builder/factory/build-localized-challenge.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#390 [TECH] Supprimer les données de calibration préexistantes lors de l'import d'une nouvelle calibration. (PIX-10099)
  scripts/populate-alpha-and-delta-column-with-csv/index-tests.js
  scripts/populate-alpha-and-delta-column-with-csv/index.js
Labels: :construction: Development in progress, Func Review OK, :rocket: Ready to Merge, team-certif, Tech Review OK

#392 [FEATURE] Exporte uniquement les traductions du référentiel cœur (PIX-10128).
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#388 [TECH] Refactoring gestion des traductions dans proxy Airtable (PIX-10085)
  api/lib/application/airtable-proxy.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/proxy-read-request-to-airtable.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/skill.js
  api/lib/infrastructure/translations/utils.js
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/scripts/migrate-skills-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/acceptance/application/airtable-proxy-controller-skill_test.js
  api/tests/acceptance/application/airtable-proxy-controller_test.js
  api/tests/unit/application/airtable-proxy_test.js
  api/tests/unit/domain/usecases/proxy-read-request-to-airtable_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
  api/tests/unit/infrastructure/translations/utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#393 [BUGFIX] Modifications depuis PixEditor : ne pas supprimer toutes les traductions (PIX-10004)
  .circleci/config.yml
  .gitignore
  .vscode/sample.settings.json
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
