Repository 1024pix/pix-editor, pull requests merged in 2023-03, with the labels that each got.

#96 [FEATURE] Mise à jour des dépendances
  api/package-lock.json
  api/package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#97 [FEATURE] Add default selected value on geographic field (PIX-3590)
  pix-editor/app/components/field/select.hbs
  pix-editor/app/components/form/challenge.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu

#98 [FEATURE] Mise a jour de la doc de rédaction de proposition sur pix éditor (PIX-7520).
  pix-editor/app/components/form/challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#100 [TECH] Passage à node 16
  .circleci/config.yml
  api/package-lock.json
  api/package.json
  docker-compose.yml
  package.json
  pix-editor/.template-lintrc.js
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review Needed, Tech Review OK

#99 [TECH] Vérifier la validités des liens contenu dans les bonnes réponses des épreuves (PIX-6190).
  api/lib/domain/usecases/validate-urls-from-release.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK
