Repository 1024pix/pix-editor, pull requests merged in 2023-07, with the labels that each got.

#117 [FEATURE] Pouvoir voir la liste paginée des tests statiques sur PixEditor (PIX-7795)
  api/lib/application/static-courses/index.js
  api/lib/application/static-courses/static-courses.js
  api/lib/domain/models/StaticCourse.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-summary-serializer.js
  api/lib/infrastructure/utils/query-params-utils.js
  api/lib/routes.js
  api/tests/acceptance/application/databases/databases-controller_test.js
  api/tests/acceptance/application/static-courses_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/airtable-builder/factory/build-course.js
  api/tests/tooling/database-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/build-course-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/static-courses/static-courses_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/utils/query-params-utils_test.js
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/controllers/authenticated/static-courses.js
  pix-editor/app/models/static-course-summary.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/static-courses.js
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/static-courses.scss
  pix-editor/app/styles/shadows.scss
  pix-editor/app/templates/authenticated/static-courses.hbs
  pix-editor/config/icons.js
  pix-editor/mirage/config.js
  pix-editor/mirage/serializers/static-course-summary.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/static-courses-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#121 [FEATURE] Pouvoir voir le détail d'un test statique sur PixEditor (PIX-7796)
  api/db/seeds/data/static-courses.js
  api/lib/application/static-courses/index.js
  api/lib/application/static-courses/static-courses.js
  api/lib/domain/models/ChallengeSummary.js
  api/lib/domain/models/StaticCourse.js
  api/lib/domain/models/StaticCourseSummary.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/static-course-summary-serializer.js
  api/tests/acceptance/application/databases/databases-controller_test.js
  api/tests/acceptance/application/static-courses_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-course.js
  api/tests/tooling/database-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/build-course-airtable-data-object.js
  api/tests/unit/application/static-courses/static-courses_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  pix-editor/app/components/card.hbs
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/controllers/authenticated/static-courses/static-course.js
  pix-editor/app/models/challenge-summary.js
  pix-editor/app/models/static-course.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/static-courses/list.js
  pix-editor/app/routes/authenticated/static-courses/static-course.js
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated.scss
  pix-editor/app/styles/authenticated/static-courses/list.scss
  pix-editor/app/styles/authenticated/static-courses/static-course.scss
  pix-editor/app/styles/components/card.scss
  pix-editor/app/styles/globals/global.scss
  pix-editor/app/styles/globals/page.scss
  pix-editor/app/styles/globals/table.scss
  pix-editor/app/templates/authenticated.hbs
  pix-editor/app/templates/authenticated/static-courses.hbs
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/loading.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/serializers/static-course.js
  pix-editor/tests/acceptance/static-courses-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#125 [FEATURE] Empêcher les utilisateurs avec un rôle "readpixonly" d'accéder aux fonctionnalités liées aux tests statiques (PIX-8589)
  api/db/seeds/seed.js
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/routes/authenticated/static-courses.js
  pix-editor/app/services/access.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#126 [BUGFIX] Le lien de PixEditor vers Airtable est invalide
  api/lib/config.js
  api/lib/infrastructure/serializers/jsonapi/config-serializer.js
  api/sample.env
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
  pix-editor/app/controllers/authenticated/competence/tubes/single.js
  pix-editor/app/models/config.js
  pix-editor/app/services/config.js
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#128 [BUGFIX] L'utilisateur ne pouvait plus créer de domaine (PIX-8612)
  pix-editor/app/models/area.js
  pix-editor/app/models/framework.js
  pix-editor/tests/unit/services/current-data-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#133 [TECH] Réparer CircleCI (Fail sur Install ChromeDriver)
  .circleci/config.yml
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#134 [TECH] Désactivation de google analytics dans TUI editor
  pix-editor/app/components/field/mde.hbs
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#124 [TECH] Migration vers embroider
  pix-editor/.eslintignore
  pix-editor/app/components/field/tutorials.js
  pix-editor/app/components/sidebar/navigation.js
  pix-editor/app/components/target-profile/pdf-export.js
  pix-editor/app/controllers/authenticated/area-management/new.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/app/controllers/authenticated/competence-management/single.js
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/controllers/authenticated/competence/prototypes/new.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives/new.js
  pix-editor/app/controllers/authenticated/competence/skills/new.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
  pix-editor/app/controllers/authenticated/competence/themes/new.js
  pix-editor/app/controllers/authenticated/competence/themes/single.js
  pix-editor/app/controllers/authenticated/competence/tubes/new.js
  pix-editor/app/controllers/authenticated/competence/tubes/single.js
  pix-editor/app/controllers/authenticated/target-profile.js
  pix-editor/app/services/storage.js
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/templates/application.hbs
  pix-editor/app/vendor/AmpleSoft-bold.js
  pix-editor/app/vendor/AmpleSoft-normal.js
  pix-editor/app/vendor/Roboto-condensed.js
  pix-editor/app/vendor/Roboto-condensedBold.js
  pix-editor/app/vendor/Roboto-condensedLight.js
  pix-editor/app/vendor/Roboto-normal.js
  pix-editor/app/vendor/pdf-assets.js
  pix-editor/config/deprecation-workflow.js
  pix-editor/ember-cli-build.js
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/area.js
  pix-editor/mirage/factories/attachment.js
  pix-editor/mirage/factories/challenge.js
  pix-editor/mirage/factories/competence.js
  pix-editor/mirage/factories/framework.js
  pix-editor/mirage/factories/skill.js
  pix-editor/mirage/factories/theme.js
  pix-editor/mirage/factories/tube.js
  pix-editor/mirage/factories/user.js
  pix-editor/mirage/serializers/application.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/login-test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#131 [BUGFIX] design des pages de tests statiques revu (PIX-8586)
  api/package-lock.json
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/controllers/authenticated/static-courses/new.js
  pix-editor/app/controllers/authenticated/static-courses/static-course/edit.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/static-courses/list.scss
  pix-editor/app/styles/authenticated/static-courses/static-course.scss
  pix-editor/app/styles/globals/notification.scss
  pix-editor/app/styles/globals/page.scss
  pix-editor/app/templates/application.hbs
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/config/environment.js
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#132 [TECH] Prévenir le commit de secrets (PIX-8664)
  .githooks/pre-commit
  api/package.json
  package.json
  pix-editor/package.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#154 [BUGFIX] Réordonner l'affichage des compétences (PIX-8760).
  pix-editor/app/models/area.js
Labels: :rocket: Ready to Merge, team-contenu

#155 [TECH] Upgrade embroider en v3
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, tech-days-up

#167 [TECH] :green_heart: Déclarer les environnements CircleCI dans des executors
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech Review OK, tech-days-up

#206 [TECH] Spécifie les version de ember-source et d'ember-data qui fonctionnent
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
