Repository 1024pix/pix-editor, pull requests merged in 2023-12, with the labels that each got.

#398 [FEATURE] Permettre de prévisualiser une épreuve dans une locale donnée (PIX-10182)
  api/lib/application/challenges/index.js
  api/lib/config.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/preview-challenge.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/sample.env
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/tooling/airtable-builder/airtable-mock-route.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/preview-challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#401 [BUGFIX] Import des traductions ne créé qu'une seule épreuve virtuelle (PIX-10218)
  api/lib/domain/usecases/import-translations.js
  api/tests/unit/domain/usecases/import-translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#396 [FEATURE] Lecture des traductions des acquis dans la release (PIX-9402)
  api/lib/domain/models/Competence.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/index.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/transformers/competence-transformer.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/skill.js
  api/lib/infrastructure/translations/utils.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/translations/utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#404 [FEATURE] Adapter la réplication pour utiliser les traductions PG des Acquis (PIX-9403)
  api/lib/domain/models/Skill.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#405 [FEATURE] Débrancher les champs traduisibles des acquis dans Airtable (PIX-9404)
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/translations/skill.js
  api/tests/acceptance/application/airtable-proxy-controller-skill_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/scripts/migrate-skills-translation-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-skill-datasource-object.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#406 [FEATURE] Ajout des traductions des acquis dans l'export Phrase (PIX-10230)
  api/lib/domain/usecases/export-translations.js
  api/lib/infrastructure/translations/skill.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#413 [TECH] Retrouve les `alternative-locales` depuis les traductions présentes.
  api/lib/application/challenges/index.js
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/transformers/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#411 [TECH] Documenter le format des challenges et créer un parser de QCU/QCM
  challenge-parser/README.md
  challenge-parser/index.js
  challenge-parser/package-lock.json
  challenge-parser/package.json
  challenge-parser/parse-qcm-solution.test.js
  challenge-parser/parse-qcm-solutions.js
  challenge-parser/parse-qcm.js
  challenge-parser/parse-qcm.test.js
  challenge-parser/parse-qcu-qcm-proposals.js
  challenge-parser/parse-qcu-qcm-proposals.test.js
  challenge-parser/parse-qcu-solution.js
  challenge-parser/parse-qcu-solution.test.js
  challenge-parser/parse-qcu.js
  challenge-parser/parse-qcu.test.js
  docs/pull_request_template.md
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#415 [FEATURE] Exporte le lien de prévisualisation dans l'outil de traduction.
  api/db/knex-database-connection.js
  api/db/migrations/20200914155337_add-users-table.js
  api/db/migrations/20210218183440_add-releases-table.js
  api/db/migrations/20220727085301_add-trainings-table.js
  api/db/migrations/20220906082935_add-read-pix-only-role.js
  api/db/migrations/20221011133651_delete-trainings.js
  api/db/migrations/20230614145342_add-static-courses-table.js
  api/db/migrations/20230616134032_add-image-url-column-to-static-courses-table.js
  api/db/migrations/20230726133054_make-static-courses-description-longer.js
  api/db/migrations/20230802085633_migrate-static-courses-from-airtable.js
  api/db/migrations/20230803133550_add-isactive-column-in-static-courses-table.js
  api/db/migrations/20230810160953_add-column-deactivation-reason-in-table-static-courses.js
  api/db/migrations/20230821122954_add-translations-table.js
  api/db/migrations/20230825091746_change-competence-translations-suffix.js
  api/db/migrations/20230905083431_drop-column-imageurl-in-table-static-courses.js
  api/db/seeds/data/static-courses.js
  api/db/seeds/data/translations.js
  api/lib/application/translations.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/domain/usecases/export-translations.js
  api/package.json
  api/tests/acceptance/application/translations_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#419 [FEATURE] Seeds : Créer des épreuves virtuelles pour les épreuves ayant des traductions supplémentaires (PIX-10311)
  api/db/seeds/data/localized-challenges.js
  api/db/seeds/data/translations.js
  api/db/seeds/seed.js
Labels: :rocket: Ready to Merge, team-contenu

#424 [FEATURE] Adapte les URLs des simulateurs avec la locale de l'épreuve (PIX-10329).
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#428 [BUGFIX] Ordre des domaines dans le panneau de navigation (PIX-10264)
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/models/framework.js
  pix-editor/tests/unit/models/framework-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#431 [BUGFIX] Changement de la locale principale de l'épreuve (PIX-10424)
  api/lib/domain/usecases/import-translations.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/scripts/fix-localized-challenges-locale/index.js
  api/scripts/migrate-challenges-translation-from-airtable/index.js
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/scripts/migrate-skills-translation-from-airtable/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#433 [FEATURE] Lit le champ `embedURL` depuis la table `localized_challenges` (PIX-10366).
  api/db/seeds/data/localized-challenges.js
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#437 [FEATURE] Script de nettoyage des localized challenges et translations (PIX-10479)
  api/scripts/cleanup-localized-challenges-and-translations/index.js
  api/scripts/fix-localized-challenges-locale/index.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#436 [FEATURE] Ajoute la langue "nl" dans les tutoriels (PIX-10167).
  api/lib/config.js
  api/lib/domain/constants.js
  api/lib/infrastructure/serializers/jsonapi/config-serializer.js
  api/tests/acceptance/application/config/config-controller_test.js
  pix-editor/app/components/form/tutorial.hbs
  pix-editor/app/components/form/tutorial.js
  pix-editor/app/models/config.js
  pix-editor/app/services/config.js
  pix-editor/tests/integration/components/form/tutorial-test.js
  pix-editor/tests/integration/components/pop-in/tutorial-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#423 [FEATURE] Ajouter une page liste des missions (PIX-10271)
  api/db/migrations/20231214105517_create-missions-table.js
  api/db/seeds/data/missions.js
  api/db/seeds/seed.js
  api/lib/application/missions/index.js
  api/lib/application/missions/mission-controller.js
  api/lib/domain/models/Mission.js
  api/lib/domain/models/index.js
  api/lib/domain/readmodels/MissionSummary.js
  api/lib/domain/readmodels/index.js
  api/lib/domain/usecases/find-all-missions.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/lib/infrastructure/translations/mission.js
  api/lib/routes.js
  api/package.json
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-mission-summary.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/domain/usecases/find-all-missions_test.js
  api/tests/unit/infrastructure/repository/competence-repository_test.js
  pix-editor/app/adapters/mission-summary.js
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/controllers/authenticated/missions/list.js
  pix-editor/app/models/mission-summary.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/missions/list.js
  pix-editor/app/templates/authenticated/missions.hbs
  pix-editor/app/templates/authenticated/missions/list.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/scenarios/default.js
  pix-editor/mirage/serializers/mission-summary.js
  pix-editor/tests/acceptance/missions/list_test.js
  pix-editor/tests/acceptance/static-courses/list-test.js
  pix-editor/tests/integration/components/sidebar/main-test.js
Labels: :rocket: Ready to Merge, Pix1d

#438 [FEATURE] Permettre l'affichage de l'embedURL pour toutes les épreuves localisées (PIX-10332)
  api/lib/application/localized-challenges.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/components/field/input.hbs
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/models/challenge.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/competence/prototypes/single/alternatives/localized.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/localized-challenge.js
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
  pix-editor/tests/acceptance/competence/prototypes/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#443 [FEATURE] Ajout du button de copie de lien pour les épreuves localisées
  pix-editor/app/components/buttons/copy-link.hbs
  pix-editor/app/components/buttons/copy-link.js
  pix-editor/app/components/field/copy.hbs
  pix-editor/app/components/field/copy.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
  pix-editor/tests/integration/components/field/copy-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#444 [REFACTOR] Ajout du bandeau sur la page de version d'un challenge
  pix-editor/app/components/competence/prototypes/challenge-header.hbs
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#445 [TECH] Monter la version de l'image postgresql
  .circleci/config.yml
  docker-compose.yml
Labels: cross-team, :rocket: Ready to Merge, team-captains

#446 [FEATURE] Ajouter le lien vers Pix Editor dans la description des clefs des épreuves (PIX-10472)
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK
