Repository 1024pix/pix-editor, pull requests merged in 2023-10, with the labels that each got.

#321 [FEATURE] Lire les champs d'épreuves traduits depuis la base de donnée PG (PIX-9447)
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations/challenge.js
  api/package.json
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#323 [FEATURE] Épreuves : Alimenter la release avec la table translations (PIX-9518)
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/translations/challenge.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#329 [BUGFIX] Impossible de créer/modifier un test statique (PIX-9523)
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#328 [FEATURE] Permettre de réactiver un test statique (PIX-9362)
  api/lib/application/static-courses/index.js
  api/lib/application/static-courses/static-courses.js
  api/lib/domain/models/StaticCourse.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/tests/acceptance/application/static-courses/put_static-course-reactivate_test.js
  pix-editor/app/adapters/static-course.js
  pix-editor/app/controllers/authenticated/static-courses/static-course/details.js
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/static-courses/activation-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#327 [BUGFIX] Bouton Actualiser KO sur la page d'une compétence (PIX-9520)
  pix-editor/app/routes/authenticated/competence.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#326 [BUGFIX] Problème chargement de la vue Acquis après modif d'un sujet (PIX-9455)
  pix-editor/app/components/sidebar/navigation.hbs
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#325 [TECH] Ne pas patcher le cache LCMS en RA/Intégration (PIX-9504)
  api/lib/application/airtable-proxy.js
  api/lib/application/challenges/index.js
  api/lib/infrastructure/pix-api-client.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/challenges/challenges_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#324 [FEATURE] Alimenter la réplication avec la table translations (PIX-9519)
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#330 [TECH] Améliorer le temps de chargement initial du frontend (PIX-9527)
  pix-editor/app/routes/authenticated.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#333 [FEATURE] Exporter les traductions au format CSV compatible avec Phrase (PIX-9538).
  api/lib/domain/usecases/export-translations.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/domain/usecases/export-translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#337 [CLEANUP] Supprime le plugin Metrics
  api/lib/infrastructure/plugins/index.js
  api/lib/infrastructure/plugins/metrics.js
  api/package-lock.json
  api/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#334 [TECH] Chargement des épreuves en lazy (PIX-9586)
  pix-editor/app/components/competence/grid/cell-i18n.hbs
  pix-editor/app/components/competence/grid/cell-i18n.js
  pix-editor/app/components/competence/grid/cell-production.hbs
  pix-editor/app/components/competence/grid/cell-production.js
  pix-editor/app/components/competence/grid/cell-quality.hbs
  pix-editor/app/components/competence/grid/cell-quality.js
  pix-editor/app/components/competence/grid/cell-workbench.hbs
  pix-editor/app/components/competence/grid/cell-workbench.js
  pix-editor/app/routes/authenticated/competence.js
  pix-editor/app/styles/_competence.scss
  pix-editor/tests/e2e/challenge.spec.js
  pix-editor/tests/e2e/login.spec.js
  pix-editor/tests/e2e/static-course.spec.js
  pix-editor/tests/integration/components/competence/grid/cell-i18n-test.js
  pix-editor/tests/integration/components/competence/grid/cell-production-test.js
  pix-editor/tests/integration/components/competence/grid/cell-quality-test.js
  pix-editor/tests/integration/components/competence/grid/grid-cell-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#338 [FEATURE] Tagguer les données exportées vers Phrase (PIX-9559)
  api/lib/domain/usecases/export-translations.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/utils/merge-stream.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/domain/usecases/export-translations_test.js
  api/tests/unit/infrastructure/utils/merge-stream_test.js
  api/tests/unit/infrastructure/utils/promise-streamer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#339 [FEATURE] Modifier la release et la réplication pour supporter l'ancien et le nouveau format des données traduisibles des épreuves (PIX-9315)
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#343 [FEATURE] Faire la recherche d'épreuve à partir des traductions (PIX-9659)
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
Labels: :rocket: Ready to Merge, team-contenu

#340 [FEATURE] Renommer puis supprimer d'airtable les colonnes traduisibles des épreuves (PIX-9317)
  api/lib/application/challenges/index.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/usecases/create-challenge.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-challenge.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/translations/challenge.js
  api/scripts/migrate-challenges-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/static-courses/get_static-course_test.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course-deactivate_test.js
  api/tests/acceptance/application/static-courses/put_static-course-reactivate_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/scripts/migrate-challenges-translation-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-release.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-challenge-datasource-object.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/release/Content_test.js
  api/tests/unit/domain/usecases/create-challenge_test.js
  api/tests/unit/domain/usecases/update-challenge_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/translations/challenge_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#345 [BUGFIX] Corrige le noms des tags a l'export
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#352 Revert "[BUMP] Update dependency node to v18.18.2"
  .circleci/config.yml
  .nvmrc
  api/package-lock.json
  api/package.json
  package-lock.json
  package.json
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: :rocket: Ready to Merge, team-contenu

#354 [FEATURE] Adapter les noms des tags pour pouvoir utiliser les filtres de Phrase (PIX-9752).
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#357 [BUGFIX] Patch du challenge quand on modifie l'illustration (PIX-9770)
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/unit/repositories/release-repository_test.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#358 [TECH] Spécifier le buildpack utilisé par Scalingo.
  .buildpacks
Labels: :rocket: Ready to Merge, Tech Review OK
