Repository 1024pix/pix-editor, pull requests merged in 2023-01, with the labels that each got.

#82 [BUGFIX] Réparer la génération du fichier pdf de présentation du référentiel (PIX-6781).
  pix-editor/app/components/target-profile/pdf-export.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#77 [CLEANUP] Supprime la compatibilité avec l'ancien format pour les textes traduits
  api/lib/domain/models/AreaForRelease.js
  api/lib/domain/models/CompetenceForRelease.js
  api/lib/domain/models/SkillForRelease.js
  api/lib/domain/models/ThematicForRelease.js
  api/lib/domain/models/TubeForRelease.js
  api/lib/domain/services/i18n-key-generator-for-release-models.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/lib/infrastructure/transformers/competence-transformer.js
  api/lib/infrastructure/transformers/skill-transformer.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/airtable-builder/factory/build-skill.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/airtable-builder/factory/build-tube.js
  api/tests/tooling/domain-builder/factory/build-area-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-area-for-release.js
  api/tests/tooling/domain-builder/factory/build-competence-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-competence-for-release.js
  api/tests/tooling/domain-builder/factory/build-skill-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-skill-for-release.js
  api/tests/tooling/domain-builder/factory/build-thematic-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-thematic-for-release.js
  api/tests/tooling/domain-builder/factory/build-tube-airtable-data-object.js
  api/tests/tooling/domain-builder/factory/build-tube-for-release.js
  api/tests/unit/domain/models/AreaForRelease_test.js
  api/tests/unit/domain/models/CompetenceForRelease_test.js
  api/tests/unit/domain/models/Content_test.js
  api/tests/unit/domain/models/SkillForRelease_test.js
  api/tests/unit/domain/models/ThematicForRelease_test.js
  api/tests/unit/domain/models/TubeForRelease_test.js
  api/tests/unit/infrastructure/serializers/airtable-serializer_test.js
  api/tests/unit/infrastructure/transformers/competence-transformer_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#85 [TECH] Déplace la création de release dans un process dédié
  api/lib/infrastructure/scheduled-jobs/check-urls-job.js
  api/lib/infrastructure/scheduled-jobs/release-job-processor.js
  api/lib/infrastructure/scheduled-jobs/release-job.js
  api/tests/unit/infrastructure/scheduled-jobs/release-job_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#83 [TECH] Ne pas lancer le check des URL lors de la création d'une release en dehors de l'environnement de production (PIX-6878).
  api/lib/config.js
  api/lib/infrastructure/scheduled-jobs/release-job-processor.js
  api/sample.env
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK
