Repository 1024pix/pix-editor, pull requests merged in 2023-06, with the labels that each got.

#108 [TECH] Mise à jour ember v4 (PIX-8190)
  pix-editor/app/components/field/files.hbs
  pix-editor/app/components/field/illustration.hbs
  pix-editor/app/components/list/alternatives.hbs
  pix-editor/app/components/list/archive.hbs
  pix-editor/app/components/list/events-log.hbs
  pix-editor/app/components/list/i18n.hbs
  pix-editor/app/components/list/notes.hbs
  pix-editor/app/components/list/prototypes.hbs
  pix-editor/app/components/list/skills.hbs
  pix-editor/app/components/list/workbench.hbs
  pix-editor/app/controllers/area-management/new.js
  pix-editor/app/controllers/competence-management/new.js
  pix-editor/app/controllers/competence.js
  pix-editor/app/controllers/competence/prototypes/new.js
  pix-editor/app/controllers/competence/prototypes/single/alternatives/new.js
  pix-editor/app/controllers/competence/skills/new.js
  pix-editor/app/controllers/competence/skills/single/archive.js
  pix-editor/app/controllers/competence/themes/new.js
  pix-editor/app/controllers/competence/tubes/new.js
  pix-editor/app/routes/application.js
  pix-editor/app/routes/area-management/new.js
  pix-editor/app/routes/competence/prototypes/single/alternatives.js
  pix-editor/app/routes/competence/skills/single/archive.js
  pix-editor/app/serializers/airtable.js
  pix-editor/app/services/id-generator.js
  pix-editor/app/templates/competence.hbs
  pix-editor/app/templates/competence/prototypes/single/alternatives.hbs
  pix-editor/app/templates/competence/skills/single.hbs
  pix-editor/app/templates/competence/skills/single/archive.hbs
  pix-editor/config/optional-features.json
  pix-editor/config/targets.js
  pix-editor/ember-cli-build.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/area-management/new-test.js
  pix-editor/tests/acceptance/competence-management/new-test.js
  pix-editor/tests/acceptance/search-test.js
  pix-editor/tests/integration/components/form/challenge-test.js
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#111 [FEATURE] Afficher les domaines ordonnés par code (PIX-8216).
  pix-editor/app/models/area.js
  pix-editor/app/models/framework.js
  pix-editor/app/services/current-data.js
  pix-editor/tests/unit/services/current-data-test.js
Labels: :rocket: Ready to Merge, team-contenu

#109 [TECH] Mettre à jour PixUi à la version v35.0.0
  pix-editor/app/components/login-form.hbs
  pix-editor/app/components/login-form.js
  pix-editor/app/components/pop-in/challenge-log.hbs
  pix-editor/app/components/pop-in/changelog.hbs
  pix-editor/app/components/pop-in/confirm-log.hbs
  pix-editor/app/components/pop-in/confirm.hbs
  pix-editor/app/components/pop-in/image.hbs
  pix-editor/app/components/pop-in/logout.hbs
  pix-editor/app/components/pop-in/new-framework.hbs
  pix-editor/app/components/pop-in/pdf-entries.hbs
  pix-editor/app/components/pop-in/select-location.hbs
  pix-editor/app/components/pop-in/single-entry.hbs
  pix-editor/app/components/pop-in/sorting.hbs
  pix-editor/app/components/pop-in/threshold-calculation.hbs
  pix-editor/app/components/pop-in/tube-level.hbs
  pix-editor/app/components/pop-in/tutorial.hbs
  pix-editor/app/controllers/login.js
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/_popin.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/login-form.scss
  pix-editor/app/styles/pages/login.scss
  pix-editor/app/templates/login.hbs
  pix-editor/ember-cli-build.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/public/assets/images/elephant.png
  pix-editor/public/assets/images/elephant_login.svg
  pix-editor/public/assets/images/elephant_main.png
  pix-editor/tests/acceptance/login-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#113 [FEATURE] Renvoit le fichier index.html en cas de 404
  api/lib/application/static/index.js
  api/lib/config.js
  api/lib/infrastructure/utils/pre-response-utils.js
  api/tests/acceptance/application/static_test.js
  api/tests/public-tests/pix-editor/index.html
Labels: :rocket: Ready to Merge, Tech Review OK

#112 [FEATURE] Reprise de données pour afficher aléatoirement les anciens QCU/QCM (PIX-7876)
  scripts/enable-shuffled-on-challenges/index.js
  scripts/package-lock.json
  scripts/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#118 [BUGFIX] La "Duplication vers" d'un acquis pour le passer d'un sujet à un autre ne fonctionne pas (PIX-8485)
  pix-editor/app/templates/authenticated/competence/skills/single.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
