Repository 1024pix/pix-editor, pull requests merged in 2023-08, with the labels that each got.

#215 [TECH] Ajout d'un script pour peupler les champs alpha et delta des challenges à partir d'un CSV
  scripts/populate-alpha-and-delta-column-with-csv/index-tests.js
  scripts/populate-alpha-and-delta-column-with-csv/index.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#170 [FEATURE] Migrer les tests statiques de Airtable vers Postgres (PIX-7793)
  api/db/migrations/20230726133054_make-static-courses-description-longer.js
  api/db/migrations/20230802085633_migrate-static-courses-from-airtable.js
  api/lib/application/databases.js
  api/lib/application/replication-data.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/datasources/airtable/course-datasource.js
  api/lib/infrastructure/datasources/airtable/index.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/transformers/course-transformer.js
  api/lib/routes.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/static-courses_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-course.js
  api/tests/tooling/airtable-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-course-postgres-data-object.js
  api/tests/tooling/domain-builder/factory/build-release.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/Content_test.js
  api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js
  api/tests/unit/infrastructure/transformers/course-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#172 [TECH] Correction du champ license des package.json
  api/package.json
  end-to-end-tests/package.json
  pix-editor/package.json
  scripts/package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review Needed

#226 [FEATURE] Faire en sorte qu'un test statique nouvellement créé soit actif par défaut (PIX-8567)
  api/db/migrations/20230802085633_migrate-static-courses-from-airtable.js
  api/db/migrations/20230803133550_add-isactive-column-in-static-courses-table.js
  api/db/seeds/data/static-courses.js
  api/lib/domain/models/StaticCourse.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/tests/tooling/database-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/build-static-course.js
  api/tests/unit/domain/models/StaticCourse_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#227 [FEATURE] Afficher le statut du test statique sur la liste des tests statiques et sur la page de détails d'un test statique (PIX-8643)
  api/db/seeds/data/static-courses.js
  api/lib/domain/readmodels/StaticCourse.js
  api/lib/domain/readmodels/StaticCourseSummary.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-serializer.js
  api/tests/acceptance/application/static-courses_test.js
  pix-editor/app/models/static-course-summary.js
  pix-editor/app/models/static-course.js
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/tests/acceptance/static-courses/details-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#231 [BUGFIX] Inverser l'ordre des challenges des tests statiques(PIX-8898)
  scripts/migrate-static-courses-from-airtable/index.js
  scripts/reverse-static-courses-challenges-order/index.js
Labels: :rocket: Ready to Merge, team-contenu

#232 [FEATURE] Ajouter l'information de statut d'un test statique dans la release afin que cette information puisse être exploitée côté Pix (PIX-8900)
  api/lib/domain/models/CourseForRelease.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#233 [FEATURE] Ajouter un lien de prévisualisation de l'épreuve dans la liste des épreuves sur la page de détails d'un test statique (PIX-8515)
  api/lib/domain/readmodels/ChallengeSummary.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-serializer.js
  api/tests/acceptance/application/static-courses/get_static-course_test.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course-deactivate_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  pix-editor/app/models/challenge-summary.js
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#235 [FEATURE] N'afficher que les tests statiques actifs par défaut et permettre à l'utilisateur de pouvoir tous les afficher (PIX-8648)
  api/lib/application/static-courses/static-courses.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/utils/knex-utils.js
  api/tests/acceptance/application/static-courses/get_static-course-summaries_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/integration/infrastructure/utils/knex-utils_test.js
  api/tests/test-helper.js
  api/tests/unit/application/static-courses/static-courses_test.js
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/routes/authenticated/static-courses/list.js
  pix-editor/app/styles/globals/table.scss
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/static-courses/deactivation-test.js
  pix-editor/tests/acceptance/static-courses/details-test.js
  pix-editor/tests/acceptance/static-courses/edition-test.js
  pix-editor/tests/acceptance/static-courses/list-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#240 [TECH] Récupérer la déclinaison du challenge (PIX-7702)
  api/lib/domain/models/ChallengeForRelease.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/unit/domain/models/Content_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix1d

#243 [FEATURE] Faire que le lien vers le test statique soit dirigé vers l'environnement de production (PIX-8949)
  pix-editor/app/models/static-course-summary.js
  pix-editor/app/models/static-course.js
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/config/icons.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#246 [FEATURE] Stocker les traductions d'une nouvelle compétence (PIX-8687)
  api/db/migrations/20230821122954_add-translations-table.js
  api/lib/application/airtable-proxy.js
  api/lib/infrastructure/logger.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations-extractors/competence.js
  api/lib/infrastructure/translations-extractors/index.js
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/tooling/database-builder/database-buffer.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/unit/infrastructure/translations-extractors/competence_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#257 [FEATURE] Permettre d'afficher dans PixEditor les traductions d'une compétence (PIX-8686)
  api/lib/application/airtable-proxy.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/index.js
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/acceptance/application/airtable-proxy-controller_test.js
  api/tests/unit/infrastructure/translations-extractors/competence_test.js
  api/tests/unit/infrastructure/translations/competence_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#259 [BUGFIX] Changer le suffixe des traductions des compétences
  api/db/migrations/20230825091746_change-competence-translations-suffix.js
  api/lib/infrastructure/translations/competence.js
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/scripts/migrate-competences-translation-from-airtable_test.js
  api/tests/unit/infrastructure/translations/competence_test.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#260 [FEATURE] Adapter la release pour insérer les translations de PG (PIX-8706)
  CHANGELOG.md
  api/lib/application/airtable-proxy.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations/competence.js
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/unit/infrastructure/translations/competence_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#254 [TECH] Utiliser eslint-plugin-n plutôt que eslint-plugin-node
  pix-editor/.eslintrc.js
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#261 [BUGFIX] Ne pas appeler `process.exit` dans les tests (PIX-9015)
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/tests/scripts/migrate-competences-translation-from-airtable_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#263 [FEATURE] Renseigner les traductions de Compétences pour la réplication via la table PG `translations`(PIX-8973).
  api/lib/application/replication-data.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#266 [BUGFIX] Problème d'enregistrement de compétence incomplète lorsque la description n'est pas renseignée (PIX-9026)
  api/lib/infrastructure/translations/competence.js
  api/tests/unit/infrastructure/translations/competence_test.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#265 [FEATURE] Adapter les seeds pour insérer les traductions dans la base PG (PIX-8986)
  api/db/seeds/data/translations.js
  api/db/seeds/seed.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/datasources/airtable/index.js
  api/lib/infrastructure/datasources/airtable/translation-datasource.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/acceptance/application/airtable-proxy-controller-refresh-cache_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/scripts/migrate-competences-translation-from-airtable_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK
