Repository 1024pix/pix-editor, pull requests merged in 2023-02, with the labels that each got.

#88 [FEATURE] Ajouter la date de validation d'une épreuve dans la table d'Airtable "Epreuves" (PIX-6541)
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/models/challenge.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#89 [FEATURE] Ajouter la date d'archivage dans Airtable à l'archivage d'une épreuve (PIX-6543)
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/models/challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#90 [FEATURE] Ajouter la date de péremption d'une épreuve (PIX-7022)
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/models/challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#91 [TECH] Récupérer les dates de : mise en production, archivage et obsolescence des épreuves en se basant sur le Changelog et les releases (PIX-5210)
  scripts/package-lock.json
  scripts/package.json
  scripts/restore-challenges-validated-and-archived-at/index.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#94 [TECH] Mise en place de Stylelint
  .circleci/config.yml
  pix-editor/.stylelintrc.json
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review Needed

#93 [TECH] Exposer les nouveaux champs de Airtable depuis LCMS (PIX-7121).
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review Needed

#95 [TECH] Active des règles de lint SCSS d'espacement
  pix-editor/.stylelintrc.json
  pix-editor/app/styles/_challenge-log.scss
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/styles/_custom-accordion.scss
  pix-editor/app/styles/_custom-basic-dropdown.scss
  pix-editor/app/styles/_custom-select.scss
  pix-editor/app/styles/_custom-sortable-group.scss
  pix-editor/app/styles/_custom-tabs.scss
  pix-editor/app/styles/_custom-tooltip.scss
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/_mde.scss
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/styles/_skill.scss
  pix-editor/app/styles/_statistics.scss
  pix-editor/app/styles/_target-profile.scss
  pix-editor/app/styles/_tube.scss
  pix-editor/app/styles/app.scss
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
