Repository 1024pix/pix-editor, pull requests merged in 2023-09, with the labels that each got.

#267 [BUGFIX] Erreur quand on vérifie la table translation (Airtable) avec un PAT (PIX-9033)
  api/lib/infrastructure/datasources/airtable/translation-datasource.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#275 [TECH] Supprimer la colonne "imageUrl" de la table des tests statiques, attribut non utilisé (PIX-9080)
  api/db/migrations/20230802085633_migrate-static-courses-from-airtable.js
  api/db/migrations/20230905083431_drop-column-imageurl-in-table-static-courses.js
  api/db/seeds/data/static-courses.js
  api/lib/domain/models/CourseForRelease.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/database-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/build-course-for-release.js
  api/tests/tooling/domain-builder/factory/build-course-postgres-data-object.js
  api/tests/unit/domain/models/Content_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#274 [BUGFIX] Logs d'erreur à tort lors de l'enregistrement de traductions (PIX-9077)
  api/lib/infrastructure/datasources/airtable/translation-datasource.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review Needed

#122 [TECH] Clarifier la procédure d'installation
  INSTALL.md
  api/sample.env
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#285 [DOC] ADR "Modulariser le code NodeJS" (PIX-9154)
  docs/adr/0005-modulariser-le-code-nodejs.md
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#293 [BUGFIX] Corriger les jobs planifiés avec le passage à ESM.
  api/lib/infrastructure/scheduled-jobs/check-urls-job-processor.cjs
  api/lib/infrastructure/scheduled-jobs/release-job-processor.cjs
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#282 [FEATURE] Exporter les traductions depuis l'interface d'admin (PIX-8977).
  api/db/seeds/seed.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/translations.js
  api/lib/domain/usecases/export-translations.js
  api/lib/infrastructure/plugins/adminjs/components/ExportComponent.jsx
  api/lib/infrastructure/plugins/adminjs/index.js
  api/lib/infrastructure/plugins/adminjs/models.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/routes.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/server.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/test-helper.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/domain/usecases/export-translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#296 [FEATURE] Personnaliser le titre de la page d'adminjs
  api/lib/infrastructure/plugins/adminjs/index.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#298 [FEATURE] Pouvoir importer les traductions dans AdminJS (PIX-8978)
  api/lib/application/translations.js
  api/lib/domain/usecases/import-translations.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/plugins/adminjs/components/ExportComponent.jsx
  api/lib/infrastructure/plugins/adminjs/components/ImportExportComponent.jsx
  api/lib/infrastructure/plugins/adminjs/index.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/translations_test.js
  api/tests/unit/application/translations_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#306 [FEATURE] Ajout des options "lien externe" et "indice" dans la liste des champs à contextualiser d'une épreuve (PIX-9287).
  pix-editor/app/components/form/challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#291 [TECH] CircleCI: Lier la version de l'executor Playwright à celle de la dépendance avec Renovate.
  .circleci/config.yml
  renovate.json
Labels: :rocket: Ready to Merge, team-contenu

#315 [FEATURE] Ajouter les champs traduisible dans la base PG lors de la création et de la modification d'une épreuve (PIX-9295)
  api/lib/application/challenges/index.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/usecases/create-challenge.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-challenge.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/translations/challenge.js
  api/lib/infrastructure/translations/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/usecases/create-challenge_test.js
  api/tests/unit/domain/usecases/update-challenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/translations/challenge_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#318 [FEATURE] Importer les traductions des épreuves dans PG depuis Airtable (PIX-9416)
  api/scripts/migrate-challenges-translation-from-airtable/index.js
  api/tests/scripts/migrate-challenges-translation-from-airtable_test.js
  api/tests/scripts/migrate-competences-translation-from-airtable_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#319 [FEATURE] Suppression des translations dans PG et Airtable (PIX-9441)
  api/lib/application/airtable-proxy.js
  api/lib/domain/usecases/update-challenge.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/datasources/airtable/translation-datasource.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/translations/challenge.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/index.js
  api/tests/acceptance/application/airtable-proxy-controller-competence_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/domain/usecases/update-challenge_test.js
  api/tests/unit/infrastructure/translations/challenge_test.js
  api/tests/unit/infrastructure/translations/competence_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#320 [BUGFIX] Traductions manquantes dans l'export PDF en anglais (PIX-7858)
  pix-editor/app/components/target-profile/pdf-export.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
