Repository 1024pix/pix-editor, pull requests merged in 2024-12, with the labels that each got.

#833 [FEATURE] Mettre à jour les icons fontawsome avec ceux du design système (PIX-14773).
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/templates/authenticated/missions/list.hbs
  pix-editor/app/templates/authenticated/missions/mission/details.hbs
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/app/templates/authenticated/whitelisted-urls/list.hbs
  pix-editor/config/environment.js
  pix-editor/config/icons.js
  pix-editor/package.json
Labels: Design Review OK, Func Review OK, :rocket: Ready to Merge, team-contenu

#842 [BUGFIX] Vue acquis prod : attendre que les tutos soient chargés (PIX-15747)
  pix-editor/app/routes/authenticated/competence/skills.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#822 [FEATURE] Sortir les compétences du proxy Airtable (PIX-15345)
  api/lib/application/airtable-proxy.js
  api/lib/application/competences/competences.js
  api/lib/application/competences/index.js
  api/lib/application/types.js
  api/lib/domain/models/Competence.js
  api/lib/domain/usecases/create-competence.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-competence.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/serializers/jsonapi/competence-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/transformers/competence-transformer.js
  api/lib/infrastructure/translations/competence.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-competence_test.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-refresh-cache_test.js
  api/tests/acceptance/application/areas_test.js
  api/tests/acceptance/application/competences/competences_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/frameworks_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-competence-datasource-object.js
  api/tests/unit/domain/models/Competence_test.js
  api/tests/unit/domain/usecases/create-competence_test.js
  api/tests/unit/domain/usecases/update-competence_test.js
  pix-editor/app/adapters/competence.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/app/models/area.js
  pix-editor/app/routes/authenticated/competence-management/new.js
  pix-editor/app/serializers/competence.js
  pix-editor/mirage/config.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#835 [FEATURE] Ne plus afficher un message d'érreur lorsqu'on annule la mise en prod des déclinaisons (PIX-14987).
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/tests/acceptance/validate-prototype-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#843 [BUGFIX] Navigation de qualité à épreuves (PIX-15748)
  pix-editor/app/routes/authenticated/challenge.js
  pix-editor/app/routes/authenticated/competence/prototypes.js
  pix-editor/tests/acceptance/search-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#846 [TECH] Monter la version de Postgres vers 15.10 sur tous les environnements de développement pour matcher avec la production (PIX-15877)
  .circleci/config.yml
  docker-compose.yml
  scalingo.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#850 [TECH] Ajouter les référentiels et les missions dans la réplication (PIX-15879)
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
