Repository 1024pix/pix-editor, pull requests merged in 2024-01, with the labels that each got.

#450 [FEATURE] Permettre la modification de l'embed URL d'une épreuve nl (PIX-10365).
  .eslintrc.yaml
  api/lib/application/localized-challenges.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/services/access.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/tests/unit/controllers/competence/prototypes/localized-test.js
  pix-editor/tests/unit/services/access-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#453 [BUGFIX] Identifiants et labels des champs textes (PIX-10605)
  pix-editor/app/components/field/textarea.hbs
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/skill.hbs
  pix-editor/app/components/form/theme.hbs
  pix-editor/app/components/form/tube.hbs
  pix-editor/app/templates/authenticated/area-management/new.hbs
  pix-editor/app/templates/authenticated/competence-management/single.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#452 [FEATURE] Afficher l'identifiant de l'épreuve localisée (PIX-10604)
  pix-editor/app/components/field/input.hbs
  pix-editor/app/components/field/textarea.hbs
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/skill.hbs
  pix-editor/app/components/form/theme.hbs
  pix-editor/app/components/form/tube.hbs
  pix-editor/app/templates/authenticated/area-management/new.hbs
  pix-editor/app/templates/authenticated/competence-management/single.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#454 [FEATURE] Ecrit le titre des embed dans la table translations (PIX-10615)
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/translations/challenge.js
  api/scripts/migrate-embed-title-translation-from-airtable/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/scripts/migrate-embed-title-translation-from-airtable_test.js
  api/tests/unit/infrastructure/translations/challenge_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#456 [FEATURE] Lire le titre des embeds depuis les traductions dans PG (PIX-10620)
  api/lib/domain/models/Challenge.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/translations/challenge.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-challenge-datasource-object.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#457 [TECH] Fixer la versions des addons de BDD pour les reviews APP
  scalingo.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#461 [BUGFIX] Augmente la taille maximale autorisée du fichier de traductions importé (PIX-10718).
  api/lib/application/translations.js
  api/lib/config.js
  api/sample.env
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#462 [FEATURE] Pouvoir rechercher une épreuve localisée par identifiant (PIX-10680)
  api/lib/application/challenges/index.js
  api/lib/application/localized-challenges.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/infrastructure/utils/query-params-utils.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/unit/infrastructure/utils/query-params-utils_test.js
  pix-editor/app/components/sidebar/search.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/routes/authenticated/challenge.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/search-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#463 [TECH] Ajouter un template custom de migration Knex
  api/db/knexfile.js
  api/db/migration-template.js
Labels: cross-team, :rocket: Ready to Merge, team-contenu, Tech Review OK

#465 [FEATURE] Ajoute la locale `nl` aux locales possibles des déclinaisons (PIX-10735).
  api/lib/domain/constants.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#449 [FEATURE] Pouvoir créer une mission (PIX-10273)
  api/db/seeds/data/missions.js
  api/lib/application/missions/index.js
  api/lib/application/missions/mission-controller.js
  api/lib/domain/usecases/create-mission.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/lib/infrastructure/translations/mission.js
  api/tests/acceptance/application/mission/post_mission_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/unit/application/healthcheck/index_test.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/infrastructure/repository/translation-repository_test.js
  pix-editor/app/adapters/mission.js
  pix-editor/app/components/form/mission.hbs
  pix-editor/app/components/form/mission.js
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/controllers/authenticated/missions/new.js
  pix-editor/app/models/framework.js
  pix-editor/app/models/mission.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/missions/new.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/missions/new.scss
  pix-editor/app/styles/components/card.scss
  pix-editor/app/templates/authenticated/missions/list.hbs
  pix-editor/app/templates/authenticated/missions/new.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/scenarios/default.js
  pix-editor/tests/acceptance/missions/creation-test.js
  pix-editor/tests/integration/components/form/missions-test.js
Labels: Pix1d

#469 Utilise un attribute static pour simplifier
  pix-editor/app/models/framework.js
Labels: :rocket: Ready to Merge, Pix1d

#466 [FEATURE] Permettre de jouer ou non en prod une épreuve traduite (PIX-10710)
  api/db/migrations/20240109160109_add-status-column-for-localized-challenges.js
  api/db/seeds/data/localized-challenges.js
  api/lib/application/localized-challenges.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/security-utils.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/usecases/import-translations.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/database-builder/factory/build-localized-challenge.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  pix-editor/app/components/competence/prototypes/challenge-header.hbs
  pix-editor/app/components/pop-in/confirm.hbs
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/services/access.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
  pix-editor/tests/unit/models/localized-challenge-test.js
  pix-editor/tests/unit/services/access-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#470 [FEATURE] Ajouter les missions à la création de release (PIX-10275)
  api/lib/domain/models/release/Content.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/domain-builder/factory/build-content-for-release.js
Labels: :rocket: Ready to Merge, Pix1d

#474 [BUGFIX] Afficher les versions traduites d'une épreuve périmée ou archivée (PIX-10770).
  api/lib/application/challenges/index.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#476 [BUGFIX] Autorise les modifications de Embed URL par un utilisateur non admin (PIX-10804).
  api/lib/application/localized-challenges.js
  api/lib/domain/errors.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/modify-localized-challenge.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/unit/domain/usecases/modify-localized-challenges_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#477 [WORKAROUND] Solution de contournement pour pouvoir importer `\"` dans Phrase (PIX-10120)
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/import-translations.js
  api/server.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#478 [TECH] Vérifier que la version de node est disponible sur Scalingo avant de la mettre à jour
  .github/workflows/check-node-version-availability-on-scalingo.yml
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#481 [FEATURE] Ajoute les épreuves traduites à la réplication (PIX-10761)
  api/lib/domain/services/translate-challenge.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#486 [FEATURE] Rattacher l'attachment à un localized challenge (PIX-10879)
  pix-editor/app/serializers/attachment.js
  pix-editor/tests/unit/serializers/attachment-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#487 [BUGFIX] Le localizedChallengeId doit se baser sur le challengeId Persistant (PIX-10884)
  pix-editor/app/serializers/attachment.js
  pix-editor/tests/unit/serializers/attachment-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#492 [FEATURE] Lister les pièces jointes et illustrations de l'épreuve par langue (PIX-10896)
  api/lib/application/challenges/index.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/services/translate-challenge.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/domain/usecases/preview-challenge.js
  api/lib/infrastructure/datasources/airtable/attachment-datasource.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-challenge-datasource-object.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/usecases/preview-challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  api/tests/unit/infrastructure/translations/challenge_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#499 [FEATURE] Ecrire dans la base PG les données traduites des domaines (PIX-9479)
  api/lib/infrastructure/translations/area.js
  api/lib/infrastructure/translations/index.js
  api/scripts/migrate-areas-translations-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy-controller-area_test.js
  api/tests/scripts/migrate-areas-translations-from-airtable_test.js
  api/tests/tooling/input-output-data-builder/factory/build-area.js
  api/tests/tooling/input-output-data-builder/factory/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#500 [FEATURE] i18n : Lecture hybride des domaines (PIX-9481)
  api/lib/domain/models/Area.js
  api/lib/domain/models/index.js
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/translations/area.js
  api/tests/acceptance/application/airtable-proxy-controller-area_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#502 [FEATURE] Déprécier les colonnes traduites des domaines de airtable (PIX-9484)
  api/lib/domain/models/Area.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/translations/area.js
  api/tests/acceptance/application/airtable-proxy-controller-area_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/scripts/migrate-areas-translations-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-area-datasource-object.js
  api/tests/unit/infrastructure/serializers/airtable-serializer_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
