Repository 1024pix/pix-editor, pull requests merged in 2024-02, with the labels that each got.

#503 [REVERT] Suppression du contournement pour les \" dans l'export Phrase (PIX-10210)
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/import-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#504 [FEATURE] Ajout d'une table de jointure entre localized challenges et attachments pour gérer ces derniers côté PG (PIX-10978)
  api/db/migrations/20240131143146_add-joint-table-of-localizedChallenges-and-attachment.js
  api/db/seeds/data/localized-challenges-attachments.js
  api/db/seeds/data/localized-challenges.js
  api/db/seeds/seed.js
  api/lib/application/airtable-proxy.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/proxy-delete-request-to-airtable.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenges-attachments-repository.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/package-lock.json
  api/package.json
  api/scripts/fill-localized-challenges-attachments/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenges-attachments-repository_test.js
  api/tests/scripts/fill-localized-challenges-attachments_test.js
  api/tests/scripts/fill-localized-challenges_test.js
  api/tests/tooling/database-builder/factory/build-localized-challenge-attachment.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/usecases/proxy-delete-request-to-airtable_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#501 [FEATURE] Permettre l'ajout d'une piece jointe ou d'une illustration sur une épreuve traduite (PIX-10934).
  pix-editor/app/components/field/files.hbs
  pix-editor/app/components/field/illustration.hbs
  pix-editor/app/components/pop-in/image.hbs
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/models/attachment.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/serializers/airtable.js
  pix-editor/app/serializers/application.js
  pix-editor/app/serializers/attachment.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/field.scss
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-attachment-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-illustration-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/localized-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#505 [BUGFIX] Changement de couleur des bordures d'un composant "SELECT"
  pix-editor/app/styles/_sidebar.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#510 [TECH] Renommer le champ `challenge.area` en `challenge.geography` (PIX-11117).
  api/lib/domain/models/Challenge.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/tooling/airtable-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-challenge-datasource-object.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/components/statistics/i18n.js
  pix-editor/app/models/challenge.js
  pix-editor/mirage/factories/challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#511 [FEATURE] Ecrire l'alternative textuel des illustrations dans la table de traduction (PIX-9296).
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/translations/attachment.js
  api/lib/infrastructure/translations/index.js
  api/tests/acceptance/application/airtable-proxy-controller-attachment_test.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-attachment-datasource-object.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/tooling/input-output-data-builder/factory/build-attachment.js
  api/tests/tooling/input-output-data-builder/factory/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#512 [FEATURE] Migre les traductions des textes alternatifs des illustrations vers la table `translations` (PIX-9505).
  api/scripts/migrate-attachments-translation-from-airtable/index.js
  api/tests/scripts/migrate-attachments-translation-from-airtable_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu

#521 [BUGFIX] Réparation des fichiers de challenges qui n'étaient pas supprimés (PIX-11213)
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/unit/component/form/challenge-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#522 [FEATURE] Script pour lister les épreuves avec des pièces jointes en double (PIX-11217)
  scripts/list-duplicated-attachments/index.js
Labels: :rocket: Ready to Merge, Tech Review OK

#533 [BUGFIX] Supprimer les pièces jointes et illustrations en doublon (PIX-11295).
  api/scripts/fix-attachments/index.js
  api/tests/acceptance/application/airtable-proxy-controller-attachment_test.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/scripts/fix-attachments_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#538 [BUGFIX] Transmettre l'illustration alt depuis l'objet épreuves plutot que sur l'attachment (PIX-11335).
  api/lib/domain/models/Attachment.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/domain/usecases/proxy-read-request-to-airtable.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/translations/attachment.js
  api/lib/infrastructure/translations/challenge.js
  api/lib/infrastructure/translations/index.js
  api/scripts/migrate-attachments-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-attachment_test.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/scripts/migrate-attachments-translation-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment-for-localized-challenge.js
  api/tests/tooling/airtable-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-attachment-datasource-object.js
  api/tests/tooling/input-output-data-builder/factory/build-attachment.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  pix-editor/app/components/field/illustration.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/models/challenge.js
  pix-editor/tests/unit/component/form/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#540 [FEATURE] Permettre de filtrer les tests statiques par nom (PIX-8886)
  api/lib/application/static-courses/static-courses.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/tests/acceptance/application/static-courses/get_static-course-summaries_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/unit/application/static-courses/static-courses_test.js
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/routes/authenticated/static-courses/list.js
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/static-courses/activation-test.js
  pix-editor/tests/acceptance/static-courses/edition-test.js
  pix-editor/tests/acceptance/static-courses/list-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#541 [BUGFIX] Fermeture de la modal d'illustration sur une épreuve NL (PIX-11355)
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#543 [FEATURE] Agrandir le nombre de lignes visibles dans le champ texte de la description d'un test statique (PIX-11377)
  pix-editor/app/components/form/static-course.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#542 [BUGFIX] Preview des challenges après suppression/remplacement de PJ/illustration (PIX-11375)
  api/lib/application/challenges/index.js
  api/lib/domain/usecases/proxy-delete-request-to-airtable.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/new.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives/new.js
  pix-editor/tests/unit/controllers/competence/prototypes/new-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#552 [BUGFIX] Impossible d'enregistrer une illustration sur une épreuve NL (PIX-11416)
  pix-editor/app/models/attachment.js
  pix-editor/tests/unit/serializers/attachment-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#548 [FEATURE] Exporte en csv seulement les épreuves validées (PIX-11219)
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#551 [FEATURE] Vérifier les colonnes du CSV avant l'import de la calibration certif V3 (PIX-11415)
  scripts/populate-alpha-and-delta-column-with-csv/index.js
  scripts/populate-alpha-and-delta-column/index-tests.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#553 [BUGFIX] Erreur 422 recherche de tutos (création modification acquis) (PIX-11423)
  pix-editor/app/components/field/tutorials.js
  pix-editor/tests/unit/component/field/tutorials-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#554 [FEATURE] Popup de rechargement lors du déploiement d'une nouvelle version
  pix-editor/app/adapters/api.js
  pix-editor/app/controllers/authenticated.js
  pix-editor/app/models/api.js
  pix-editor/app/serializers/api.js
  pix-editor/tests/unit/controllers/authenticated-test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#547 [FEATURE] Afficher les tags d'un test statique sur la liste (PIX-11378)
  api/db/migrations/20240226092502_create-static-course-tag-tables.js
  api/db/seeds/data/static-courses.js
  api/lib/domain/readmodels/StaticCourseSummary.js
  api/lib/domain/readmodels/StaticCourseTag.js
  api/lib/domain/readmodels/index.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-serializer.js
  api/tests/acceptance/application/static-courses/get_static-course-summaries_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/database-builder/factory/build-release.js
  api/tests/tooling/database-builder/factory/build-static-course-tag.js
  api/tests/tooling/database-builder/factory/build-static-course.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-area-for-release.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/tooling/domain-builder/factory/build-competence-for-release.js
  api/tests/tooling/domain-builder/factory/build-content-for-release.js
  api/tests/tooling/domain-builder/factory/build-course-for-release.js
  api/tests/tooling/domain-builder/factory/build-domain-release.js
  api/tests/tooling/domain-builder/factory/build-framework-for-release.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/build-skill-for-release.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-static-course-summary.js
  api/tests/tooling/domain-builder/factory/build-static-course.js
  api/tests/tooling/domain-builder/factory/build-tag.js
  api/tests/tooling/domain-builder/factory/build-thematic-for-release.js
  api/tests/tooling/domain-builder/factory/build-tube-for-release.js
  api/tests/tooling/domain-builder/factory/build-tutorial-for-release.js
  api/tests/tooling/domain-builder/factory/index.js
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/models/static-course-summary.js
  pix-editor/app/models/static-course-tag.js
  pix-editor/app/styles/authenticated/static-courses/list.scss
  pix-editor/app/styles/globals/table.scss
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/config/environment.js
  pix-editor/mirage/serializers/static-course-summary.js
  pix-editor/tests/acceptance/static-courses/list-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#555 [FEATURE] Voir les tags des tests statiques dans leur page de détails. (PIX-11381)
  api/db/seeds/data/static-courses.js
  api/lib/domain/readmodels/StaticCourse.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/static-course-serializer.js
  api/tests/acceptance/application/static-courses/get_static-course-summaries_test.js
  api/tests/acceptance/application/static-courses/get_static-course_test.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course-deactivate_test.js
  api/tests/acceptance/application/static-courses/put_static-course-reactivate_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/database-builder/factory/build-static-course-tag.js
  api/tests/tooling/domain-builder/factory/build-challenge-summary.js
  api/tests/tooling/domain-builder/factory/build-static-course-read.js
  api/tests/tooling/domain-builder/factory/index.js
  pix-editor/app/models/static-course.js
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/mirage/serializers/static-course.js
  pix-editor/tests/acceptance/static-courses/details-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
