Repository 1024pix/pix-editor, pull requests merged in 2024-08, with the labels that each got.

#719 [FEATURE] Ne pas autoriser la validation d'une mission si celle-ci contient au moins une épreuve non validée (PIX-13613).
  api/lib/domain/usecases/update-mission.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/tests/integration/domain/usecases/update-mission_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  pix-editor/app/controllers/authenticated/missions/mission/edit.js
  pix-editor/config/environment.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/missions/edit_test.js
  pix-editor/tests/test-helper.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#725 [FEATURE] Ajout de contrôle sur la liste des Epreuves quand la Mission est VALIDATED (Pix-13589)
  api/lib/infrastructure/repositories/mission-repository.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#724 [BUGFIX] Migration focus: Ne migrer que les acquis de Pix coeur (PIX-13709)
  api/scripts/move-skills-to-focus/index.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#704 [FEATURE] Autoriser le filtre par tags sur les tests statiques (PIX-13404)
  api/lib/application/static-courses/static-courses.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/unit/application/static-courses/static-courses_test.js
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/routes/authenticated/static-courses/list.js
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/static-courses/list-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#734 [BUGFIX] Un mauvais usage de initSentry fait planté l'application. (PIX-13749)
  pix-editor/app/app.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#738 [FEAUTURE] Ajouter un media d'introduction à une mission (Pix-13630)
  api/db/migrations/20240807144411_add_introduction_media_into_mission_table.js
  api/lib/domain/models/Mission.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/package.json
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/domain/usecases/update-mission_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/unit/application/missions/mission-controller_test.js
  pix-editor/app/adapters/mission.js
  pix-editor/app/components/form/mission.hbs
  pix-editor/app/components/form/mission.js
  pix-editor/app/controllers/authenticated/missions/mission/edit.js
  pix-editor/app/models/mission.js
  pix-editor/app/templates/authenticated/missions/mission/details.hbs
  pix-editor/tests/acceptance/missions/edit_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#739 [TECH] Nettoyage des données de l'enquête anti-spoil (PIX-13812)
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: :rocket: Ready to Merge, team-contenu

#743 [TECH] Passage des configs ESLint de .yaml à .cjs
  .eslintrc.yaml
  api/.eslintrc.cjs
  api/.eslintrc.yaml
  pix-editor/.eslintrc.cjs
  pix-editor/.eslintrc.js
  scripts/.eslintrc.cjs
  scripts/.eslintrc.yaml
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#744 [TECH] Utiliser le nouveau format de config ESLint
  api/.eslintrc.cjs
  api/eslint.config.cjs
  api/package-lock.json
  api/package.json
  pix-editor/.eslintignore
  pix-editor/.eslintrc.cjs
  pix-editor/eslint.config.cjs
  pix-editor/package-lock.json
  pix-editor/package.json
  scripts/.eslintrc.cjs
  scripts/eslint.config.cjs
  scripts/package-lock.json
  scripts/package.json
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#742 [FEATURE] Préciser le type de média de l'URL d'introduction de mission (pix-13843)
  api/db/migrations/20240812092902_add_columns_into_mission_table.js
  api/lib/domain/errors.js
  api/lib/domain/models/Mission.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/domain/usecases/create-mission.js
  api/lib/domain/usecases/update-mission.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/domain/usecases/create-mission_test.js
  api/tests/integration/domain/usecases/update-mission_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/mission-serializer_test.js
  pix-editor/app/adapters/mission.js
  pix-editor/app/components/form/mission.hbs
  pix-editor/app/components/form/mission.js
  pix-editor/app/controllers/authenticated/missions/mission/edit.js
  pix-editor/app/models/mission.js
  pix-editor/app/styles/authenticated/missions/new.scss
  pix-editor/app/templates/authenticated/missions/mission/details.hbs
  pix-editor/tests/acceptance/missions/edit_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#748 [TECH] Montée de version ESLint v9
  api/db/knex-database-connection.js
  api/lib/application/security-pre-handlers.js
  api/lib/infrastructure/utils/url-utils.js
  api/package-lock.json
  api/package.json
  pix-editor/app/components/login-form.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/missions/new.js
  pix-editor/app/controllers/authenticated/static-courses/static-course/details.js
  pix-editor/app/routes/authenticated/challenge.js
  pix-editor/mirage/config.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/unit/services/storage-test.js
  scripts/package-lock.json
  scripts/package.json
  scripts/restore-challenges-validated-and-archived-at/index.js
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#740 [FEATURE] Générer la liste des embeds utilisés par pix-editor (PIX-13835).
  api/lib/application/embeds.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/translations.js
  api/lib/domain/usecases/get-embed-list.js
  api/lib/infrastructure/plugins/adminjs/components/Card.jsx
  api/lib/infrastructure/plugins/adminjs/components/Dashboard.jsx
  api/lib/infrastructure/plugins/adminjs/components/GetEmbedList.jsx
  api/lib/infrastructure/plugins/adminjs/components/Loader.jsx
  api/lib/infrastructure/plugins/adminjs/components/assets/pe-admin.svg.jsx
  api/lib/infrastructure/plugins/adminjs/index.js
  api/lib/routes.js
  api/tests/acceptance/application/embeds_test.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/domain/usecases/get-embed-list_test.js
Labels: Design Review OK, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#751 [TECH] Amélioration de performance de la création de release (PIX-13991)
  api/lib/domain/models/Mission.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/transformers/index.js
  api/lib/infrastructure/transformers/mission-transformer.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/unit/infrastructure/transformers/mission-transformer_test.js
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#750 [BUGFIX] Pouvoir passer une mission en validée même si elle contient des acquis périmés, archivés ou en construction (Pix-13942)
  api/lib/application/missions/mission-controller.js
  api/lib/domain/errors.js
  api/lib/domain/services/mission-validator.js
  api/lib/domain/usecases/create-mission.js
  api/lib/domain/usecases/update-mission.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/mission/post_mission_test.js
  api/tests/acceptance/application/mission/put_mission_test.js
  api/tests/integration/domain/services/mission-validator_test.js
  api/tests/integration/domain/usecases/create-mission_test.js
  api/tests/integration/domain/usecases/update-mission_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/domain/services/mission-validator_test.js
  pix-editor/app/controllers/authenticated/missions/mission/edit.js
  pix-editor/app/controllers/authenticated/missions/new.js
  pix-editor/app/models/mission.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#752 [FEATURE] Patcher le cache quand on clone un acquis (PIX-13780)
  api/lib/application/skills/skills.js
  api/lib/domain/usecases/clone-skill.js
  api/lib/infrastructure/event-notifier/updated-record-notifier.js
  api/tests/unit/domain/usecases/clone-skill_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
