Repository 1024pix/pix-editor, pull requests merged in 2024-07, with the labels that each got.

#696 [BUGFIX] Export des URLs externes: crash sur certaines URLs (PIX-13253)
  api/lib/domain/usecases/export-external-urls-from-release.js
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/domain/usecases/export-external-urls-from-release_test.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#698 [BUGFIX] Ajout d'une clé primaire sur localized_challenges-attachments (PIX-13359)
  api/db/migrations/20240710091831_localized-challenges-attachements-pkey.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#697 [FEATURE] Ne pas afficher les déclinaisons périmées par défaut (PIX-12631)
  pix-editor/app/components/alternatives.hbs
  pix-editor/app/components/alternatives.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives.js
  pix-editor/app/templates/authenticated/competence/prototypes/single/alternatives.hbs
  pix-editor/tests/integration/components/alternatives-test.js
  pix-editor/tests/integration/components/list/alternatives-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/single/alternatives-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#702 [BUGFIX] Rectification des données de responsivité renvoyées false pour les Tubes for Release (PIX-13493)
  api/lib/domain/models/Challenge.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#699 [FEATURE] Ajout des propriétés d'accessibilité des challenges dans la release (PIX-13351)
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/unit/domain/models/ChallengeForRelease_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#703 Amélioration du test du ChallengeForRelease pour l'ajout des propriétés accessibility1 & 2
  api/tests/unit/domain/models/ChallengeForRelease_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#705 [TECH] Améliorer le script de passage en focus afin d'avoir la correspondance entre les ID des épreuves avant/après (PIX-13363)
  api/scripts/move-skills-to-focus/index.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#707 [FEATURE] Ajout du statut "expérimental" des missions (PIX-13584).
  api/db/migrations/20240729140413_change-active-missions-to-validated-missions.js
  api/db/seeds/data/missions.js
  api/lib/application/missions/mission-controller.js
  api/lib/domain/models/Mission.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/mission/put_mission_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/tooling/domain-builder/factory/build-mission-summary.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/unit/application/missions/mission-controller_test.js
  pix-editor/app/components/form/mission.js
  pix-editor/app/controllers/authenticated/missions/list.js
  pix-editor/app/models/mission-summary.js
  pix-editor/app/models/mission.js
  pix-editor/app/routes/authenticated/missions/list.js
  pix-editor/app/templates/authenticated/missions/list.hbs
  pix-editor/app/templates/authenticated/missions/mission/details.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/missions/list_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#711 [FEATURE] Exclu les missions inactive de la `release` (PIX-13588)
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#718 [TECH] Filtrer l'ajout des nouvelle clef de traduction par scriptExectId (PIX-13702)
  api/scripts/upload-multi-locales-to-phrase/index.js
  api/tests/scripts/upload-multi-locales-to-phrase_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK
