Repository 1024pix/pix-editor, pull requests merged in 2024-05, with the labels that each got.

#652 [FEATURE] Ajouter les URLs à consulter renseignées au niveau des épreuves dans la moulinette des URLs cassées (PIX-11736)
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/scheduled-jobs/check-urls-job-processor.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, team-contenu, Tech Review OK

#660 [FEATURE] Ne pas checker les URLs des épreuves proposées (PIX-12411)
  api/lib/domain/usecases/validate-urls-from-release.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#661 [FEATURE] Améliorer le champ d'URLs externes (PIX-12014)
  pix-editor/app/components/field/textarea.hbs
  pix-editor/app/components/field/textarea.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/competence/prototypes/single.js
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#663 [BUMP] Montée de version node : 20.12.0 vers 20.13.0 + montée de version pixui
  .circleci/config.yml
  .nvmrc
  api/package-lock.json
  api/package.json
  package-lock.json
  package.json
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: :rocket: Ready to Merge, team-contenu, dependencies

#669 [FEATURE] Ajouter le néerlandais dans la liste des langues disponibles sur les vues Epreuves et Acquis (PIX-12645)
  pix-editor/app/components/competence/competence-header.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#670 [TECH] Suppression de la vue internationale inutilisée (PIX-12654)
  pix-editor/app/components/competence/competence-header.js
  pix-editor/app/components/competence/grid/cell-i18n.hbs
  pix-editor/app/components/competence/grid/cell-i18n.js
  pix-editor/app/components/competence/grid/grid-cell.hbs
  pix-editor/app/components/competence/grid/grid-cell.js
  pix-editor/app/components/list/i18n.hbs
  pix-editor/app/components/list/i18n.js
  pix-editor/app/controllers/authenticated/competence/i18n/single.js
  pix-editor/app/styles/_competence.scss
  pix-editor/app/styles/_i18n.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/templates/authenticated/competence/i18n/index.hbs
  pix-editor/app/templates/authenticated/competence/i18n/single.hbs
  pix-editor/tests/integration/components/competence/grid/cell-i18n-test.js
  pix-editor/tests/integration/components/competence/grid/grid-cell-test.js
  pix-editor/tests/integration/components/list/i18n-test.js
  pix-editor/tests/unit/controllers/competence/i18n/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#674 [BUGFIX] Utiliser l'id persistant des thématiques dans le code + écrire la traduction des noms des thématiques "workbench" (PIX-12726)
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/scripts/fill-missing-thematics-name-in-translations-table/index.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-thematic_test.js
  api/tests/scripts/migrate-thematics-translations-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/input-output-data-builder/factory/build-competence.js
  api/tests/tooling/input-output-data-builder/factory/build-thematic.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#677 [BUGFIX] Vérifie la validité des thématiques de la mission via l'id persistant.
  pix-editor/app/components/form/mission.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior
