Repository 1024pix/pix-editor, pull requests merged in 2024-03, with the labels that each got.

#556 [FEATURE] Envoi des traductions dans phrase (Pix-11414)
  api/lib/application/phrase.js
  api/lib/application/translations.js
  api/lib/config.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/plugins/adminjs/components/ImportExportComponent.jsx
  api/lib/infrastructure/utils/stream-to-promise.js
  api/lib/routes.js
  api/package-lock.json
  api/package.json
  api/sample.env
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/test-helper.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#557 [FEATURE] Écrire le champ Géographie des épreuves dans PG (PIX-11088)
  api/db/migrations/20240228133540_add-column-localized-challenge-geography.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Geography.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/package-lock.json
  api/package.json
  api/scripts/migrate-localized-challenges-geography/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/scripts/migrate-localized-challenges-geography_test.js
  api/tests/tooling/database-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Geography_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#567 [FEATURE] Télécharger les traductions depuis Phrase (PIX-11512)
  api/lib/application/phrase.js
  api/lib/domain/usecases/download-translation-from-phrase.js
  api/lib/domain/usecases/import-translations.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/plugins/adminjs/components/ImportExportComponent.jsx
  api/tests/acceptance/application/phrase_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#568 [FEATURE] Ajoute les Localized Challenge au panneau d'administration.
  api/lib/infrastructure/plugins/adminjs/index.js
  api/lib/infrastructure/plugins/adminjs/models.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#569 [BUGFIX] URL pour vérifier la version d'API
  pix-editor/app/adapters/api.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#570 [BUGFIX] Corrige le rechargement de la page
  pix-editor/app/controllers/authenticated.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#558 [FEATURE] Pouvoir définir des tags à la création et à la modification des tests statiques (PIX-11371)
  api/db/migrations/20240229093500_set-static-courses-tags-link-colums-as-not-null.js
  api/lib/application/static-course-tags/index.js
  api/lib/application/static-course-tags/static-course-tags.js
  api/lib/application/static-courses/static-courses.js
  api/lib/domain/models/StaticCourse.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/static-course-repository.js
  api/lib/infrastructure/repositories/static-course-tag-repository.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/static-course-tag-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/static-course-tags/get_static-course-tags_test.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/integration/infrastructure/repositories/static-course-repository_test.js
  api/tests/tooling/domain-builder/factory/build-static-course.js
  api/tests/unit/application/static-courses/static-courses_test.js
  api/tests/unit/domain/models/StaticCourse_test.js
  pix-editor/app/adapters/static-course.js
  pix-editor/app/components/form/static-course.hbs
  pix-editor/app/components/form/static-course.js
  pix-editor/app/controllers/authenticated/static-courses/list.js
  pix-editor/app/controllers/authenticated/static-courses/new.js
  pix-editor/app/controllers/authenticated/static-courses/static-course/edit.js
  pix-editor/app/routes/authenticated/static-courses/new.js
  pix-editor/app/routes/authenticated/static-courses/static-course/edit.js
  pix-editor/app/styles/authenticated/static-courses/static-course.scss
  pix-editor/app/styles/globals/page.scss
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/new.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/edit.hbs
  pix-editor/config/environment.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/static-courses/creation-test.js
  pix-editor/tests/acceptance/static-courses/edition-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#576 [FEATURE] Supprime les clés non mentionnées après l'envoi des traductions sur Phrase (PIX-11547).
  api/lib/domain/usecases/delete-unmentioned-keys-after-upload.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/scheduled-jobs/create-queue.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job-processor.cjs
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job-processor.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job.js
  api/lib/infrastructure/scheduled-jobs/index.js
  api/tests/integration/domain/usecases/delete-unmentioned-keys-after-upload_test.js
  api/tests/test-helper.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
  api/tests/unit/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#575 [FEATURE] Création de script pour ajouter des tags de tests statiques (PIX-11538)
  api/scripts/create-tags-for-static-courses/index.js
  api/tests/scripts/create-tags-for-static-courses/create-tags-for-static-courses_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#579 [TECH] Supprimer les translations dans Airtable qui ne référencent aucune entité pour alléger l'exécution des seeds en local et en RA (PIX-11556)
  api/scripts/delete-unreferenced-translations/index.js
  api/tests/scripts/delete-unreferenced-translations_test.js
  api/tests/tooling/airtable-builder/airtable-builder.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/airtable-builder/factory/build-translation.js
  api/tests/tooling/airtable-builder/factory/build-tube.js
  api/tests/tooling/airtable-builder/factory/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu

#588 [FEATURE] Exporter les traductions vers phrase après que le job de la release soit finit (PIX-11220)
  api/lib/application/phrase.js
  api/lib/application/translations.js
  api/lib/config.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/scheduled-jobs/check-urls-job-processor.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job-processor.js
  api/lib/infrastructure/scheduled-jobs/job-process.js
  api/lib/infrastructure/scheduled-jobs/release-job-processor.js
  api/lib/infrastructure/scheduled-jobs/upload-translation-job-processor.cjs
  api/lib/infrastructure/scheduled-jobs/upload-translation-job-processor.js
  api/lib/infrastructure/scheduled-jobs/upload-translation-job.js
  api/sample.env
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
  api/tests/unit/infrastructure/scheduled-jobs/release-job_test.js
  api/tests/unit/infrastructure/scheduled-jobs/upload-translation-job-processor_test.js
  scalingo.json
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#593 [FEATURE] Ecrire dans la base PG les données traduites des sujets (PIX-9409).
  api/lib/infrastructure/translations/index.js
  api/lib/infrastructure/translations/tube.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-tube_test.js
  api/tests/tooling/input-output-data-builder/factory/build-tube.js
  api/tests/tooling/input-output-data-builder/factory/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#590 [TECH] Lire le champ "Géographie" depuis les localized_challenges de la base PG (PIX-11090)
  api/db/seeds/data/localized-challenges.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Geography.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/import-translations.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/build-translation.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Geography_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/domain/usecases/preview-challenge_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/repository/competence-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#594 [TECH] Copie les champs traduisible des sujets depuis airtable vers la base postgres (PIX-9410)
  api/scripts/migrate-tubes-translations-from-airtable/index.js
  api/tests/scripts/migrate-tubes-translations-from-airtable_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#592 [FEATURE] Ajouter les fonctions de synchronisation de et vers Phrase dans Pix-Editor (PIX-11621).
  pix-editor/app/adapters/phrase.js
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/controllers/authenticated/synchronize-translations.js
  pix-editor/app/models/phrase.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/synchronize-translations.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/synchronize-translations.scss
  pix-editor/app/templates/authenticated/synchronize-translations.hbs
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/synchronize_translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#597 [FEATURE] Lien vers les trads de l'épreuve dans Phrase (PIX-11504)
  api/lib/application/challenges/index.js
  api/lib/config.js
  api/lib/domain/usecases/get-phrase-translations-url.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/sample.env
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/server/index.js
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#598 [BUGFIX] Filtrer les acquis pour n'envoyer que les "actif" à Phrase (PIX-11645)
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/domain/models/release/SkillForRelease.js
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/unit/domain/models/ChallengeForRelease_test.js
  api/tests/unit/domain/models/SkillForRelease_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#608 [TECH] Désactivation temporaire de la synchro Phrase dans la release (PIX-11665)
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job.js
  api/lib/infrastructure/scheduled-jobs/release-job-processor.js
  api/tests/unit/infrastructure/scheduled-jobs/release-job_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#616 [TECH] Supprimer le warning pour la géographie dans les seeds
  api/db/seeds/data/localized-challenges.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#607 [FEATURE] Afficher et pouvoir modifier le champ géographie au niveau d'une épreuve traduite (PIX-11092).
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#617 [TECH] Ne pas copier les traductions importées dans Airtable
  api/lib/domain/usecases/import-translations.js
  api/tests/unit/domain/usecases/import-translations_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#610 [BUGFIX] Terminer de supprimer les données traduisibles liées aux sujets (PIX-11666).
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/lib/infrastructure/translations/tube.js
  api/tests/scripts/migrate-tubes-translations-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-tube.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-tube-datasource-object.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#618 [FEATURE] Renommer "Synchroniser les traductions" en "Récupérer les traductions" (PIX-11673)
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/templates/authenticated/synchronize-translations.hbs
  pix-editor/tests/acceptance/synchronize_translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#619 [FEATURE] Filtrer les sujets qui n'ont aucun acquis actif lors de l'export des traductions (PIX-11690)
  api/lib/domain/usecases/export-translations.js
  api/tests/acceptance/application/translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#624 [FEATURE] Preview d'épreuve avec Pix App dans la langue de l'épreuve (PIX-11717)
  api/lib/config.js
  api/lib/domain/usecases/preview-challenge.js
  api/sample.env
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/unit/domain/usecases/preview-challenge_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#625 [FEATURE] Ajouter les champs spoil à l'acquis pour la réplication (PIX-11762)
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#623 [FEATURE] Afficher l'url des embed calculée par défaut pour les épreuves traduites (PIX-11507).
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/mirage/factories/challenge.js
  pix-editor/tests/acceptance/localized-challenge-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/localized-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#632 [TECH] Envoyer le résultat des tests API et pix-editor a circleci
  .circleci/config.yml
  api/vitest.config.js
  pix-editor/package.json
  pix-editor/testem.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#626 [FEATURE] Lire les traductions des thématiques dans PG (PIX-9474)
  api/lib/domain/models/Thematic.js
  api/lib/domain/models/index.js
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/translations/thematic.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-thematic_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/tooling/domain-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#635 [FEATURE] Renommer et supprimer les colonnes traduites des thématiques de Airtable (PIX-9477)
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/translations/thematic.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-thematic_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-thematic-datasource-object.js
  pix-editor/app/models/competence.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
