Repository 1024pix/pix-editor, pull requests merged in 2024-11, with the labels that each got.

#800 [FEATURE] Connecter la vue challenges production à l’overview (PIX-14424)
  api/lib/domain/readmodels/CompetenceOverview.js
  api/lib/infrastructure/serializers/jsonapi/competence-overview-serializer.js
  api/tests/acceptance/application/competences/overviews_test.js
  pix-editor/app/adapters/competence-overview.js
  pix-editor/app/components/competence/competence-footer.hbs
  pix-editor/app/components/competence/competence-footer.js
  pix-editor/app/components/competence/competence-grid-thematic.hbs
  pix-editor/app/components/competence/competence-grid-thematic.js
  pix-editor/app/components/competence/competence-grid-theme.hbs
  pix-editor/app/components/competence/competence-grid-theme.js
  pix-editor/app/components/competence/competence-grid-tube.hbs
  pix-editor/app/components/competence/competence-grid-tube.js
  pix-editor/app/components/competence/competence-grid.hbs
  pix-editor/app/components/competence/competence-grid.js
  pix-editor/app/components/competence/grid/cell-production.hbs
  pix-editor/app/components/competence/grid/cell-production.js
  pix-editor/app/components/competence/grid/grid-cell.hbs
  pix-editor/app/components/competence/grid/grid-cell.js
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/controllers/authenticated/competence/prototypes.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives-loading.js
  pix-editor/app/models/competence-overview.js
  pix-editor/app/routes/authenticated/competence/prototypes.js
  pix-editor/app/routes/authenticated/competence/prototypes/new.js
  pix-editor/app/routes/authenticated/competence/prototypes/single.js
  pix-editor/app/routes/authenticated/competence/prototypes/single/alternatives.js
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/styles/_global.scss
  pix-editor/app/templates/authenticated/competence.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single-loading.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single/alternatives-loading.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/prototypes/list-test.js
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
  pix-editor/tests/acceptance/competence/prototypes/single-test.js
  pix-editor/tests/acceptance/create-challenge-alternative-test.js
  pix-editor/tests/acceptance/create-challenge-test.js
  pix-editor/tests/acceptance/localized-challenge-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-attachment-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-illustration-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-attachment-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-illustration-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-test.js
  pix-editor/tests/acceptance/search-test.js
  pix-editor/tests/integration/components/competence/competence-grid-test.js
  pix-editor/tests/integration/components/competence/competence-grid-thematic-test.js
  pix-editor/tests/integration/components/competence/grid/cell-production-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#803 [BUGFIX] Erreur 500 sur le endpoint /competences/{id}/overviews/challenges-production (PIX-15211)
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/tests/acceptance/application/competences/overviews_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#797 [FEATURE] Permettre de consulter la liste des URLs sur liste blanche pour la moulinette (PIX-15180)
  api/db/migrations/20241104214702_add-whitelisted-urls-table.js
  api/db/seeds/data/whitelisted-urls.js
  api/db/seeds/seed.js
  api/lib/application/whitelisted-urls/index.js
  api/lib/domain/models/WhitelistedUrl.js
  api/lib/domain/models/index.js
  api/lib/domain/readmodels/WhitelistedUrl.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/whitelisted-url-read-repository.js
  api/lib/infrastructure/serializers/jsonapi/whitelisted-url-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/whitelisted-urls/whitelisted-urls_test.js
  api/tests/integration/infrastructure/repositories/whitelisted-url-read-repository_test.js
  api/tests/tooling/database-builder/factory/build-user.js
  api/tests/tooling/database-builder/factory/build-whitelisted-url.js
  api/tests/tooling/database-builder/factory/index.js
  api/tests/tooling/domain-builder/factory/build-user.js
  api/tests/tooling/domain-builder/factory/build-whitelisted-url.js
  api/tests/tooling/domain-builder/factory/index.js
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/main.js
  pix-editor/app/components/whitelisted-urls/list.hbs
  pix-editor/app/components/whitelisted-urls/list.js
  pix-editor/app/controllers/authenticated/whitelisted-urls/list.js
  pix-editor/app/models/whitelisted-url.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/whitelisted-urls.js
  pix-editor/app/routes/authenticated/whitelisted-urls/list.js
  pix-editor/app/services/access.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/whitelisted-urls/list.scss
  pix-editor/app/templates/authenticated/whitelisted-urls.hbs
  pix-editor/app/templates/authenticated/whitelisted-urls/list.hbs
  pix-editor/config/icons.js
  pix-editor/mirage/config.js
  pix-editor/mirage/serializers/whitelisted-url.js
  pix-editor/tests/acceptance/whitelisted-urls/list-test.js
  pix-editor/tests/integration/components/whitelisted-urls/list-test.js
  pix-editor/tests/unit/services/access-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#798 [FEATURE] Je veux pouvoir supprimer une URL de la liste blanche (PIX-15181)
  api/lib/application/types.js
  api/lib/application/whitelisted-urls/index.js
  api/lib/domain/errors.js
  api/lib/domain/models/User.js
  api/lib/domain/models/WhitelistedUrl.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/whitelisted-url-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/whitelisted-urls/whitelisted-urls_test.js
  api/tests/integration/infrastructure/repositories/whitelisted-url-repository_test.js
  api/tests/tooling/domain-builder/factory/build-whitelisted-url.js
  api/tests/unit/domain/models/User_test.js
  api/tests/unit/domain/models/WhitelistedUrl_test.js
  api/tests/unit/infrastructure/utils/error-manager_test.js
  pix-editor/app/components/whitelisted-urls/list.hbs
  pix-editor/app/controllers/authenticated/whitelisted-urls/list.js
  pix-editor/app/templates/authenticated/whitelisted-urls/list.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/serializers/whitelisted-url.js
  pix-editor/tests/acceptance/whitelisted-urls/list-test.js
  pix-editor/tests/integration/components/whitelisted-urls/list-test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#805 [TECH] Optimisation du chargement de la route authenticated
  pix-editor/app/routes/authenticated.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#806 [TECH] Sortir les référentiels du proxy Airtable (PIX-15250)
  api/lib/application/frameworks.js
  api/lib/domain/models/Framework.js
  api/lib/domain/models/index.js
  api/lib/domain/usecases/create-framework.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/airtable/framework-datasource.js
  api/lib/infrastructure/repositories/framework-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/transformers/framework-transformer.js
  api/lib/infrastructure/transformers/index.js
  api/lib/routes.js
  api/tests/acceptance/application/frameworks_test.js
  api/tests/tooling/airtable-builder/factory/build-framework.js
  api/tests/tooling/domain-builder/factory/build-framework.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-framework-datasource-object.js
  api/tests/tooling/domain-builder/factory/index.js
  api/tests/unit/infrastructure/datasources/airtable/framework-datasource_test.js
  pix-editor/app/adapters/framework.js
  pix-editor/app/models/framework.js
  pix-editor/app/serializers/framework.js
  pix-editor/mirage/config.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#804 [FEATURE] Connecter la vue Épreuves Atelier avec le CompetenceOverview (PIX-14523)
  api/lib/application/competences/overviews.js
  api/lib/domain/readmodels/CompetenceOverview.js
  api/lib/domain/usecases/get-competence-challenges-workbench-overview.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/acceptance/application/competences/overviews_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  pix-editor/app/components/competence/competence-grid-tube.hbs
  pix-editor/app/components/competence/competence-grid-tube.js
  pix-editor/app/components/competence/grid/cell-workbench.hbs
  pix-editor/app/components/competence/grid/cell-workbench.js
  pix-editor/app/components/competence/grid/grid-cell.hbs
  pix-editor/app/components/competence/grid/grid-cell.js
  pix-editor/app/models/challenge.js
  pix-editor/app/routes/authenticated/competence/prototypes.js
  pix-editor/app/routes/authenticated/competence/prototypes/list.js
  pix-editor/app/templates/authenticated/competence/prototypes/list-loading.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/prototypes/list-test.js
  pix-editor/tests/acceptance/competence/prototypes/single-test.js
  pix-editor/tests/acceptance/create-challenge-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/integration/components/competence/competence-grid-thematic-test.js
  pix-editor/tests/integration/components/competence/grid/cell-workbench-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#799 [FEATURE] Je veux pouvoir ajouter une URL à la liste blanche (PIX-15182)
  api/lib/application/whitelisted-urls/index.js
  api/lib/domain/errors.js
  api/lib/domain/models/WhitelistedUrl.js
  api/lib/infrastructure/repositories/whitelisted-url-read-repository.js
  api/lib/infrastructure/repositories/whitelisted-url-repository.js
  api/lib/infrastructure/utils/error-manager.js
  api/tests/acceptance/application/whitelisted-urls/whitelisted-urls_test.js
  api/tests/integration/infrastructure/repositories/whitelisted-url-read-repository_test.js
  api/tests/integration/infrastructure/repositories/whitelisted-url-repository_test.js
  api/tests/unit/domain/models/WhitelistedUrl_test.js
  api/tests/unit/infrastructure/utils/error-manager_test.js
  pix-editor/app/components/form/whitelisted-url.hbs
  pix-editor/app/components/form/whitelisted-url.js
  pix-editor/app/controllers/authenticated/whitelisted-urls/new.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/whitelisted-urls/list.js
  pix-editor/app/routes/authenticated/whitelisted-urls/new.js
  pix-editor/app/services/access.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated/whitelisted-urls/new.scss
  pix-editor/app/templates/authenticated/whitelisted-urls/list.hbs
  pix-editor/app/templates/authenticated/whitelisted-urls/new.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/whitelisted-urls/creation-test.js
  pix-editor/tests/integration/components/form/whitelisted-url-test.js
  pix-editor/tests/unit/services/access-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#808 [FEATURE] Sortir les domaines du proxy Airtable (PIX-15253)
  api/lib/application/airtable-proxy.js
  api/lib/application/areas.js
  api/lib/application/types.js
  api/lib/domain/models/Area.js
  api/lib/domain/models/release/AreaForRelease.js
  api/lib/domain/usecases/create-area.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/airtable/area-datasource.js
  api/lib/infrastructure/repositories/area-repository.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/serializers/jsonapi/area-serializer.js
  api/lib/infrastructure/serializers/jsonapi/framework-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/transformers/area-transformer.js
  api/lib/infrastructure/transformers/index.js
  api/lib/infrastructure/translations/area.js
  api/lib/infrastructure/translations/utils.js
  api/lib/routes.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-area_test.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller_test.js
  api/tests/acceptance/application/areas_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/frameworks_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-area-datasource-object.js
  api/tests/unit/repositories/release-repository_test.js
  pix-editor/app/adapters/area.js
  pix-editor/app/routes/authenticated/area-management/new.js
  pix-editor/app/serializers/area.js
  pix-editor/mirage/config.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#816 [BUGFIX] Toutes les compétences ne sont pas chargées (PIX-15300)
  pix-editor/app/adapters/airtable.js
  pix-editor/app/adapters/attachment.js
  pix-editor/app/adapters/competence.js
  pix-editor/app/adapters/note.js
  pix-editor/app/adapters/skill.js
  pix-editor/app/adapters/theme.js
  pix-editor/app/adapters/tube.js
  pix-editor/app/adapters/tutorial.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#792 [FEATURE] Prendre en compte la whitelist des URLs dans la moulinette (PIX-6043)
  api/lib/domain/models/WhitelistedUrl.js
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/scheduled-jobs/check-urls-job-processor.js
  api/tests/unit/domain/models/WhitelistedUrl_test.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#817 [FEATURE] Pour les tutoriels, ne faire remonter que les URLs qui ont été KO au moins deux fois d'affilé dans la moulinette (PIX-15002)
  api/db/migrations/20241114093733_create-tutorial-ko-urls-table.js
  api/lib/infrastructure/repositories/url-repository.js
  api/scripts/initialize-tutorial-ko-urls-table-content.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#818 [TECH] Ajouter les attributs "title" et "airtableId" dans le modèle "CompetenceOverview" (PIX-15307)
  api/lib/application/competences/overviews.js
  api/lib/domain/readmodels/CompetenceOverview.js
  api/lib/domain/usecases/get-competence-challenges-production-overview.js
  api/lib/domain/usecases/get-competence-challenges-workbench-overview.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/serializers/jsonapi/competence-overview-serializer.js
  api/tests/acceptance/application/competences/overviews_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-competence.js
  pix-editor/app/models/competence-overview.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#820 [BUGFIX] La moulinette des URLs KO ne marche plus pour les tutoriels (PIX-15320)
  api/db/migrations/20241118095718_drop-primary-column-in-tutorial-ko-urls.js
  api/db/migrations/20241118100619_add-primary-and-tutorial-id-columns-in-table-tutorial_ko_urls.js
  api/lib/infrastructure/repositories/url-repository.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#823 [DESIGN] Changement du loader
  pix-editor/app/components/loader.hbs
  pix-editor/app/templates/authenticated/competence-loading.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/list-loading.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single-loading.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single/alternatives-loading.hbs
  pix-editor/app/templates/authenticated/loading.hbs
  pix-editor/app/templates/authenticated/static-courses/loading.hbs
  pix-editor/app/templates/loading.hbs
  pix-editor/public/assets/images/elephant_loader.gif
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#821 [FEATURE] Création de la V2 de la vue épreuves production (PIX-15287)
  package-lock.json
  package.json
  pix-editor/app/components/competence-overview-skill.gjs
  pix-editor/app/components/competence-overview.gjs
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/v2/competence-overview.js
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/competence-overview-skill.scss
  pix-editor/app/styles/components/competence-overview.scss
  pix-editor/app/templates/authenticated/v2/competence-overview.hbs
  pix-editor/app/templates/authenticated/v2/loading.hbs
  pix-editor/eslint.config.cjs
  pix-editor/mirage/config.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
  pix-editor/tests/integration/components/competence-overview-skill-test.gjs
Labels: Design Review OK, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#829 [TECH] Remplacer le loader de la V2 par le nouveau loader
  pix-editor/app/templates/authenticated/v2/loading.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#830 [BUGFIX] Création d’un proto depuis la vue workbench (PIX-15405)
  pix-editor/app/controllers/authenticated/competence.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
