Repository 1024pix/pix-editor, pull requests merged in 2024-09, with the labels that each got.

#755 [FEATURE] Déplacer la logique de clonage côté back (PIX-13710)
  api/lib/application/skills/index.js
  api/lib/application/skills/skills.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Skill.js
  api/lib/domain/usecases/clone-skill.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/scripts/fix-cloned-attachments/index.js
  api/scripts/move-skills-to-focus/index.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/static-courses/put_static-course-reactivate_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/scripts/fix-cloned-attachments_test.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/tooling/airtable-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-skill-datasource-object.js
  api/tests/tooling/input-output-data-builder/factory/build-skill.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/usecases/clone-skill_test.js
  api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
  pix-editor/app/adapters/skill.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
  pix-editor/app/models/skill.js
  pix-editor/app/serializers/skill.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/skills/single-test.js
  pix-editor/tests/unit/controllers/competence/skills/single-test.js
  pix-editor/tests/unit/models/skill-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#756 [BUGFIX] Crash de l’appli lorsqu’on rafraîchit sur détail acquis/épreuve (PIX-14085)
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#757 [FEATURE] Ajout des titres de thématique en tant que nom d'étapes dans les missions releasées (PIX-13849)
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/transformers/mission-transformer.js
  api/tests/unit/infrastructure/transformers/mission-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#759 [TECH] Exposer `airtableId` dans nos models (PIX-14272)
  api/lib/domain/models/Competence.js
  api/lib/domain/models/Thematic.js
  api/lib/domain/models/Tube.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/datasources/airtable/competence-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/transformers/index.js
  api/lib/infrastructure/transformers/thematic-transformer.js
  api/lib/infrastructure/transformers/tube-transformer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/competence-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/tooling/domain-builder/factory/build-competence.js
  api/tests/tooling/domain-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/build-tube.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-competence-datasource-object.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-thematic-datasource-object.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-tube-datasource-object.js
  api/tests/unit/infrastructure/transformers/thematic-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#760 [TECH] Internationalisation de l'alternative textuelle au média d'introduction dans les missions
  api/db/migrations/20240916072624_drop_column_introductionMediaAlt_from_missions.js
  api/lib/domain/models/Mission.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/lib/infrastructure/translations/mission.js
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/mission/put_mission_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/domain/services/mission-validator_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/mission-serializer_test.js
  api/tests/unit/infrastructure/transformers/mission-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#766 [BUGFIX] Supprimer le champ `url externe à consulter` casse l'enregistrement de l'épreuve (PIX-14455).
  pix-editor/app/components/field/toggle-field.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/tests/integration/components/field/toggle-field-test.js
  pix-editor/tests/unit/controllers/competence/prototypes/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#767 [TECH] Récupérer la liste des embeds url depuis la release.
  api/lib/domain/usecases/get-embed-list.js
  api/tests/acceptance/application/embeds_test.js
  api/tests/tooling/domain-builder/factory/build-domain-release.js
  api/tests/unit/domain/usecases/get-embed-list_test.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#769 [BUGFIX] :bug: Ne lève pas une erreur quand il n'y a pas de nom au tube (pix-14512)
  api/lib/infrastructure/transformers/mission-transformer.js
  api/tests/unit/infrastructure/transformers/mission-transformer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior
