Repository 1024pix/pix-editor, pull requests merged in 2024-06, with the labels that each got.

#678 [BUGFIX] Trie les versions alternatives dans les missions de la release (PIX-12789).
  api/lib/infrastructure/repositories/mission-repository.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#676 [TECH] Déplacer la logique de duplication d'acquis côté back (PIX-12733)
  api/lib/application/localized-challenges.js
  api/lib/application/security-pre-handlers.js
  api/lib/application/security-utils.js
  api/lib/application/skills/index.js
  api/lib/application/skills/skills.js
  api/lib/config.js
  api/lib/domain/models/Attachment.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/release/SkillForRelease.js
  api/lib/domain/usecases/clone-skill.js
  api/lib/domain/usecases/import-translations.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/attachment-datasource.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/lib/infrastructure/utils/storage.js
  api/lib/routes.js
  api/scripts/fill-localized-challenges/index.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/unit/application/security-pre-handlers_test.js
  api/tests/unit/domain/models/Attachment_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/usecases/clone-skill_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
  api/tests/unit/infrastructure/utils/storage_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK, Tchao Airtable !

#681 [BUGFIX] Corriger l'ordre des challenge quand la déclinaison est undefined (Pix-12881)
  api/lib/infrastructure/repositories/mission-repository.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK, Pix-Junior

#680 [FEATURE] Ecrire un script pour passer en masse des acquis en focus (PIX-12844)
  api/db/migrations/20240614094115_add-historic-focus-table.js
  api/db/migrations/20240614134253_add-table-focus-phrase.js
  api/lib/config.js
  api/lib/domain/models/Attachment.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/Translation.js
  api/lib/infrastructure/airtable.js
  api/lib/infrastructure/datasources/airtable/attachment-datasource.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/scripts/move-skills-to-focus/index.js
  api/scripts/upload-multi-locales-to-phrase/index.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/attachment-repository_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/scripts/upload-multi-locales-to-phrase_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/tooling/input-output-data-builder/factory/build-attachment.js
  api/tests/unit/domain/models/Attachment_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/usecases/clone-skill_test.js
  api/tests/unit/infrastructure/datasources/airtable/datasource_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#682 [BUGFIX] Echec lors du clone des attachments pour les épreuves localisées pour le script de passage en focus (PIX-13061)
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/usecases/clone-skill.js
  api/lib/infrastructure/datasources/airtable/attachment-datasource.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/scripts/move-skills-to-focus/index.js
  api/tests/integration/infrastructure/repositories/attachment-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/usecases/clone-skill_test.js
  api/tests/unit/infrastructure/datasources/airtable/attachment-datasource_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#683 [BUGFIX] Attachment incomplet lors du clonage sur Airtable (PIX-13064)
  api/lib/domain/models/LocalizedChallenge.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#686 [FEATURE] Traduction auto des URLs d'embeds Astro (PIX-12527)
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/integration/infrastructure/repositories/attachment-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/scripts/migrate-attachments-translation-from-airtable_test.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/tests/acceptance/localized-challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#689 [BUGFIX] Corriger le problème d'attachment lors du passage en focus en masse (PIX-13098)
  api/db/migrations/20240621123457_add-script-execution-id-column-for-focus-phrase.js
  api/db/migrations/20240621123508_add-script-execution-id-column-for-historic-focus.js
  api/db/migrations/20240624090645_add-previous-entity-id-in-focus-phrase-table.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Skill.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/utils/storage.js
  api/scripts/fix-cloned-attachments/index.js
  api/scripts/move-skills-to-focus/index.js
  api/tests/integration/infrastructure/repositories/attachment-repository_test.js
  api/tests/scripts/fix-cloned-attachments_test.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/Skill_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#690 [BUGFIX] Le script pour corriger le script de passage en masse des focus ne prend pas la bonne date (PIX-)
  api/scripts/fix-cloned-attachments/index.js
  api/tests/scripts/fix-cloned-attachments_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#691 [BUGFIX] Oublie d'historiser dans la BDD quand ça se passe bien (PIX-13164)
  api/scripts/fix-cloned-attachments/index.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#692 [BUGFIX] Rétablir les statuts des épreuves malencontreusement périmées suite au script de passage en masse des acquis en focus (PIX-13173)
  api/scripts/fix-obsolete-cloned-challenges/index.js
  api/tests/scripts/fix-obsolete-cloned-challenges_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#662 [FEATURE] Automatiser l'export de la liste des URLs externes (PIX-12467)
  api/index.js
  api/lib/config.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/domain/models/release/Release.js
  api/lib/domain/usecases/export-external-urls-from-release.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/url-repository.js
  api/lib/infrastructure/scheduled-jobs/check-urls-job-processor.js
  api/lib/infrastructure/scheduled-jobs/export-external-url-list-job-processor.cjs
  api/lib/infrastructure/scheduled-jobs/export-external-url-list-job-processor.js
  api/lib/infrastructure/scheduled-jobs/export-external-url-list-job.js
  api/lib/infrastructure/utils/url-utils.js
  api/sample.env
  api/scripts/check-url.js
  api/scripts/dev/export-external-url.js
  api/scripts/get-external-urls-list/index.js
  api/tests/tooling/domain-builder/factory/build-domain-release.js
  api/tests/unit/domain/models/ChallengeForRelease_test.js
  api/tests/unit/domain/models/Release_test.js
  api/tests/unit/domain/usecases/export-external-urls-from-release_test.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#687 [TECH] Reporter les valeurs des champs "sélection unique/multiples" des entités Airtable dans les modèles correspondants côté API (PIX-13086)
  api/db/seeds/data/localized-challenges.js
  api/lib/domain/models/Area.js
  api/lib/domain/models/Attachment.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/Skill.js
  api/lib/domain/models/release/AreaForRelease.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/domain/models/release/SkillForRelease.js
  api/lib/domain/models/release/TutorialForRelease.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/lib/infrastructure/transformers/tube-transformer.js
  api/scripts/move-skills-to-focus/index.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/acceptance/application/static-courses/post_static-course_test.js
  api/tests/acceptance/application/static-courses/put_static-course_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/integration/infrastructure/repositories/area-repository_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenges-attachments-repository_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/scripts/fix-attachments_test.js
  api/tests/scripts/migrate-localized-challenges-geography_test.js
  api/tests/scripts/move-skills-to-focus_test.js
  api/tests/tooling/domain-builder/factory/build-area-for-release.js
  api/tests/tooling/domain-builder/factory/build-area.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/tooling/domain-builder/factory/build-challenge.js
  api/tests/tooling/domain-builder/factory/build-release.js
  api/tests/tooling/domain-builder/factory/build-skill-for-release.js
  api/tests/tooling/domain-builder/factory/build-skill.js
  api/tests/tooling/domain-builder/factory/build-tutorial-for-release.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-area-datasource-object.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-challenge-datasource-object.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-skill-datasource-object.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-tutorial-datasource-object.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/domain/usecases/modify-localized-challenges_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  api/tests/unit/repositories/release-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK, Tchao Airtable !
