Repository 1024pix/pix-editor, pull requests merged in 2024-10, with the labels that each got.

#771 [TECH] Utiliser un service plutot que passer par le model pour synchroniser les traductions (PIX-14629)
  pix-editor/app/adapters/phrase.js
  pix-editor/app/controllers/authenticated/synchronize-translations.js
  pix-editor/app/models/phrase.js
  pix-editor/app/routes/authenticated/synchronize-translations.js
  pix-editor/app/services/phrase.js
  pix-editor/tests/unit/services/phrase-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#768 [BUGFIX] Utilise l'ID persistant plutôt que le `RecordId` (pix-14380)
  pix-editor/app/routes/authenticated/missions/mission/details.js
  pix-editor/tests/acceptance/missions/details_test.js
Labels: :rocket: Ready to Merge, Pix-Junior

#772 [FEATURE] :sparkles: Ajoute un champ pour spécifier l'image de la carte de mission (pix-14588)
  api/db/migrations/20241004083929_add-card-image-to-mission.js
  api/db/seeds/data/missions.js
  api/lib/domain/models/Mission.js
  api/lib/domain/models/release/MissionForRelease.js
  api/lib/infrastructure/repositories/mission-repository.js
  api/lib/infrastructure/serializers/jsonapi/mission-serializer.js
  api/tests/acceptance/application/mission/get_mission_test.js
  api/tests/acceptance/application/mission/post_mission_test.js
  api/tests/acceptance/application/mission/put_mission_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/mission-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/domain-builder/factory/build-mission.js
  api/tests/unit/application/missions/mission-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/mission-serializer_test.js
  api/tests/unit/infrastructure/transformers/mission-transformer_test.js
  pix-editor/app/adapters/mission.js
  pix-editor/app/components/form/mission.hbs
  pix-editor/app/components/form/mission.js
  pix-editor/app/controllers/authenticated/missions/mission/edit.js
  pix-editor/app/models/mission.js
  pix-editor/app/templates/authenticated/missions/mission/details.hbs
  pix-editor/tests/acceptance/missions/creation-test.js
  pix-editor/tests/acceptance/missions/edit_test.js
  pix-editor/tests/integration/components/form/missions-test.js
Labels: :rocket: Ready to Merge, Pix-Junior

#773 [BUGFIX] Valider un prototype ne rend pas actif son acquis (PIX-14700).
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#774 [TECH] Valider le type de l'id dans la route `GET /api/releases/:id` (PIX-14706)
  api/lib/application/releases.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#775 [BUGFIX] Permettre d'acceder au version traduite d'une déclinaison (PIX-14710)
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives/new.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/competence/prototypes/single/alternatives/single.js
  pix-editor/tests/acceptance/localized-challenge-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#776 [TECH] harmoniser les champs de qualité entre le prototype et ses déclinaisons (PIX-14677)
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Skill.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#777 [FEATURE] Ajout de 5 nouveaux attributs "qualité" concernant une épreuve sur Pix-Editor (PIX-14531)
  api/db/migrations/20241007143215_add-require-gafam-website-access-column-in-localized-challenges-table.js
  api/db/migrations/20241007144236_add-is-incompatible-ipad-certif-column-in-challenges.js
  api/db/migrations/20241007144326_add-deaf-and-hard-of-hearing-column-in-challenges.js
  api/db/migrations/20241009135328_add-is-awareness-challenge-column-in-challenges.js
  api/db/migrations/20241009135432_add-to-rephrase-column-in-challenges.js
  api/db/seeds/data/localized-challenges.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/scripts/migrate-localized-challenges-geography_test.js
  api/tests/tooling/database-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/domain/usecases/preview-challenge_test.js
  api/tests/unit/infrastructure/datasources/airtable/datasource_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  pix-editor/app/components/field/quality.hbs
  pix-editor/app/components/field/quality.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/form/challenge.js
  pix-editor/app/models/challenge.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/models/tube.js
  pix-editor/app/routes/authenticated/competence/prototypes/new.js
  pix-editor/app/routes/authenticated/competence/skills/single.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/field/quality.scss
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/app/templates/authenticated/competence/skills/single.hbs
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence/skills/single-test.js
  pix-editor/tests/acceptance/create-challenge-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/integration/components/alternatives-test.js
  pix-editor/tests/unit/models/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#778 [BUGFIX] Ascenseur remonte tout seul lors de l'édition d'une épreuve proposée, lorsqu'on souhaite modifier la valeur d'un champ "Qualité" (PIX-14877)
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/static-courses/static-course/details.hbs
  pix-editor/package-lock.json
  pix-editor/package.json
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#780 [TECH] Permettre le chargement de modèles au changement des query params `view` et `languageFilter` (PIX-14422)
  pix-editor/app/components/competence/competence-header.hbs
  pix-editor/app/components/competence/competence-header.js
  pix-editor/app/components/competence/grid/cell-skill.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/routes/authenticated/competence.js
  pix-editor/app/routes/authenticated/competence/i18n/index.js
  pix-editor/app/routes/authenticated/competence/i18n/single.js
  pix-editor/app/routes/authenticated/competence/prototypes/single.js
  pix-editor/app/routes/authenticated/competence/skills.js
  pix-editor/tests/acceptance/search-test.js
  pix-editor/tests/integration/components/competence/competence-grid-tube-test.js
  pix-editor/tests/integration/components/competence/competence-header-test.js
  pix-editor/tests/integration/components/competence/grid/cell-skill-test.js
  pix-editor/tests/unit/controllers/competence-management/new-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#783 [BUGFIX] Pour les champs qualité, dans la liste des choix possibles on pouvait choisir une option "vide" (PIX-14925)
  pix-editor/app/components/field/quality.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#784 [BUGFIX] Le champ embedURL n'était pas prérempli lorsqu'on crée une déclinaison ou qu'on duplique une épreuve (PIX-14926)
  pix-editor/app/models/challenge.js
  pix-editor/tests/unit/models/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#782 [BUGFIX] Empêcher la création d'une déclinaison avec une version `undefined` (PIX-14943)
  pix-editor/app/controllers/authenticated/competence/prototypes/single/alternatives/new.js
  pix-editor/app/models/challenge.js
  pix-editor/tests/unit/models/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#793 [FEATURE] Ajouter l'option `Acquis non pertinent` au select `Sourds et malentendants` (PIX-14996).
  api/db/migrations/20241025085413_alter-column-death-and-hard-of-hearing-extend-length.js
  api/lib/domain/models/LocalizedChallenge.js
  pix-editor/app/components/field/quality.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#790 [BUGFIX] Les pièces jointes des épreuves traduites ne s'affichent pas (PIX-14941)
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#794 [BUGFIX] Impossible d'afficher une épreuve lorsque l'embedURL de l'épreuve est invalide (PIX-14419)
  api/lib/domain/models/LocalizedChallenge.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/tests/integration/components/form/challenge-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#795 [FEATURE] Route pour récupérer les données de la page "Épreuves -> En Production" (PIX-14423)
  api/lib/application/competences/index.js
  api/lib/application/competences/overviews.js
  api/lib/application/types.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Tube.js
  api/lib/domain/readmodels/CompetenceOverview.js
  api/lib/domain/readmodels/index.js
  api/lib/domain/usecases/get-competence-challenges-production-overview.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/datasources/airtable/challenge-datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/repositories/tube-repository.js
  api/lib/infrastructure/serializers/jsonapi/competence-overview-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/routes.js
  api/tests/acceptance/application/competences/overviews_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/skill-repository_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/integration/infrastructure/repositories/tube-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/airtable-builder/factory/build-tube.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-tube-datasource-object.js
  api/tests/tooling/input-output-data-builder/factory/build-tube.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK
