Repository 1024pix/pix-editor, pull requests merged in 2025-03, with the labels that each got.

#882 [BUGFIX] Utilisation de `findUrlsInMarkdown()` sur champs qui ne sont pas du markdown (PIX15982)
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#897 [FEATURE] Envoyer les clés `fr` dans les nouveaux projets Phrase séparés par domaine (PIX-16832)
  api/lib/application/translations.js
  api/lib/config.js
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/tests/acceptance/application/translations_test.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#899 [FEATURE] Réparer le script `delete-unmentioned-keys` (PIX-17001)
  api/lib/domain/usecases/delete-unmentioned-keys-after-upload.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job-processor.js
  api/lib/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/integration/domain/usecases/delete-unmentioned-keys-after-upload_test.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
  api/tests/unit/infrastructure/scheduled-jobs/delete-unmentioned-keys-after-upload-job_test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#903 [FEAT] Le bouton de switch à la v2 ne fonctionne pas partout (PIX-16702)
  pix-editor/app/models/competence-overview.js
  pix-editor/app/routes/authenticated/competence/prototypes/single.js
  pix-editor/tests/acceptance/v2/navigation-v1-v2_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#902 [BUGFIX] Le bouton de fermeture de la liste des localized challenges ne fonctionnait pas (PIX-16453)
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/app/routes/authenticated/v2/competence-overview/localized-challenges.js
  pix-editor/app/templates/authenticated/v2/competence-overview/localized-challenges.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#904 [FEATURE] Importer les clef de traduction depuis les nouveaux projets Phrase séparés par domaine (PIX-16834).
  api/lib/application/challenges/index.js
  api/lib/config.js
  api/lib/domain/usecases/download-translation-from-phrase.js
  api/lib/domain/usecases/get-phrase-translations-url.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/unit/domain/usecases/download-translation-from-phrase_test.js
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/app/controllers/authenticated/competence/prototypes/localized.js
  pix-editor/app/models/competence.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/routes/authenticated/v2.js
  pix-editor/app/routes/authenticated/v2/competence-overview/localized-challenges.js
  pix-editor/app/templates/authenticated/v2/competence-overview/localized-challenges.hbs
  pix-editor/tests/acceptance/competence/prototypes/localized-test.js
  pix-editor/tests/acceptance/localized-challenge-test.js
  pix-editor/tests/integration/components/challenges-production/localized-challenges-production-test.gjs
  pix-editor/tests/unit/models/competence-test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#907 [BUGFIX] Fix affichage des légendes des tableaux d'épreuves en V2
  pix-editor/app/components/competence-overview/competence-overview.gjs
Labels: Design Review OK, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#909 [BUGFIX] Le bouton d'expand de la liste des localized challenges a disparu. (PIX-17146)
  pix-editor/app/components/challenges-production/challenges-production.gjs
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/app/templates/authenticated/v2/competence-overview/localized-challenges.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#911 [TECH] Afficher un avertissement quand on commit un `console.log`
  .githooks/pre-commit
Labels: cross-team, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#922 [TECH] Utilisation de PixTable dans la whitelist de la moulinette des URLs cassées (PIX-16641)
  pix-editor/app/components/whitelisted-urls/list.hbs
  pix-editor/app/components/whitelisted-urls/list.js
  pix-editor/app/controllers/authenticated/whitelisted-urls/list.js
  pix-editor/app/styles/authenticated/whitelisted-urls/list.scss
  pix-editor/app/styles/globals/table.scss
  pix-editor/tests/acceptance/whitelisted-urls/list-test.js
  pix-editor/tests/integration/components/whitelisted-urls/list-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#929 [BUGFIX] Les pages du générateur de profil cible et de l'atelier workbench ne sont plus accessibles (pix-17266)
  pix-editor/app/adapters/application.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#928 [TECH] Petit ménage après sortie des acquis du proxy Airtable
  api/lib/infrastructure/translations/skill.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller_test.js
  compose.yml
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#931 [CHORES] Nettoyage de code
  pix-editor/app/components/competence/competence-grid.js
  pix-editor/app/styles/_global.scss
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#915 [FEATURE] Rendre indisponible le bouton des versions alternatives si le challenge est périmé ou archivé (PIX-14993)
  pix-editor/app/components/alternatives.hbs
  pix-editor/app/components/alternatives.js
  pix-editor/tests/integration/components/alternatives-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
