Repository 1024pix/pix-editor, pull requests merged in 2025-10, with the labels that each got.

#1144 [TECH] Revoir le chargement des traductions des épreuves (PIX-19685)
  api/lib/application/skills/index.js
  api/lib/application/skills/skills.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/usecases/get-skill-localized-challenges-production.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/skill-serializer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/skills/index_test.js
  api/tests/unit/domain/usecases/get-skill-localized-challenges-production_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
  pix-editor/app/adapters/localized-challenge.js
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/app/models/challenge-locale.js
  pix-editor/app/models/challenge.js
  pix-editor/app/routes/authenticated/v2/competence-overview/localized-challenges.js
  pix-editor/app/templates/authenticated/v2/competence-overview/localized-challenges.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/serializers/challenge.js
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
  pix-editor/tests/acceptance/v2/competence-overview/navigation-primary-localized_test.js
  pix-editor/tests/integration/components/challenges-production/localized-challenges-production-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1139 [TECH] Migrer le composant CopyLink vers le format gjs
  pix-editor/app/components/buttons/copy-link.gjs
  pix-editor/app/components/buttons/copy-link.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#1147 [TECH] Corrige les erreurs de lint dans Pix Editor.
  pix-editor/app/components/buttons/copy-link.gjs
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#1148 [TECH] exporter les traductions en prenant en compte leur référentiel (PIX-19898)
  api/lib/application/translations.js
  api/lib/config.js
  api/lib/domain/usecases/download-translation-from-phrase.js
  api/lib/domain/usecases/export-translations.js
  api/lib/domain/usecases/upload-translation-to-phrase.js
  api/lib/infrastructure/plugins/adminjs/components/ImportExportComponent.jsx
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/replication-data-controller_test.js
  api/tests/acceptance/application/translations_test.js
  api/tests/unit/domain/usecases/download-translation-from-phrase_test.js
  api/tests/unit/domain/usecases/upload-translation-to-phrase_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
