Repository 1024pix/pix-editor, pull requests merged in 2025-04, with the labels that each got.

#908 [BUGFIX] Affichage erroné de l'état des traductions dans la v2 (PIX-16456)
  api/lib/infrastructure/serializers/jsonapi/skill-serializer.js
  api/tests/acceptance/application/skills/index_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#932 [TECH] Retirer le fun
  pix-editor/app/components/competence/competence-grid.js
  pix-editor/app/styles/_global.scss
Labels: :rocket: Ready to Merge, team-contenu

#935 [FEATURE] Purge de l'ancien code de Phrase (PIX-16835)
  api/lib/config.js
  api/lib/domain/usecases/download-translation-from-phrase.js
  api/lib/domain/usecases/get-phrase-translations-url.js
  api/sample.env
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/unit/domain/usecases/download-translation-from-phrase_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#936 [FEATURE] Exposer les données de traduction des entités du contenu pédagogique pour la réplication (PIX-16799)
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/tests/acceptance/application/replication-data_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#942 [TECH] Suppression du script de nettoyage de données dans Intégration
  api/scripts/reset-learning-content-in-integration-environment.js
  api/tests/scripts/reset-learning-content-in-integration-environment_test.js
Labels: :rocket: Ready to Merge, team-contenu

#938 [FEATURE] Ne pas afficher les liens de traduction vers Phrase quand l'épreuve est fr-fr (PIX-17041)
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/eslint.config.mjs
  pix-editor/tests/integration/components/challenges-production/localized-challenges-production-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#946 [FEATURE] Retirer toute mention du terme whitelist (PIX-17449)
  pix-editor/app/components/form/whitelisted-url.hbs
  pix-editor/app/components/whitelisted-urls/list.hbs
  pix-editor/app/controllers/authenticated/whitelisted-urls/list.js
  pix-editor/app/controllers/authenticated/whitelisted-urls/new.js
  pix-editor/app/controllers/authenticated/whitelisted-urls/whitelisted-url/edit.js
  pix-editor/app/templates/authenticated/whitelisted-urls/new.hbs
  pix-editor/app/templates/authenticated/whitelisted-urls/whitelisted-url/edit.hbs
  pix-editor/tests/acceptance/whitelisted-urls/creation-test.js
  pix-editor/tests/acceptance/whitelisted-urls/edition-test.js
  pix-editor/tests/acceptance/whitelisted-urls/list-test.js
  pix-editor/tests/integration/components/form/whitelisted-url-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#944 [FEATURE] Remettre à disposition les translations dans la réplication
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/tests/acceptance/application/replication-data_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#948 [TECH] Dans l'endpoint /api/replication-data, envoyer les données de réplication dans le flux attribut par attribut, et non plus d'un seul bloc
  api/lib/infrastructure/utils/promise-streamer.js
Labels: :rocket: Ready to Merge

#949 [TECH] S'assurer que le stream est toujours fonctionnel avant d'écrire dedans
  api/lib/infrastructure/utils/promise-streamer.js
Labels: :rocket: Ready to Merge, Tech Review OK

#947 [TECH] Retirer à nouveau les traductions des données de la répli
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#950 [BUGFIX] Les ids donnés à la volée lors de la création des données de réplication pour les traductions n'étaient pas uniques + rétablissement du code lié à l'ajout des traductions dans la répli
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/replication-data_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#952 [TECH] Ajout de logs pour essayer de comprendre le problème lors de la récupération des données de la réplication
  api/lib/infrastructure/utils/promise-streamer.js
Labels: :rocket: Ready to Merge

#953 [TECH] Je vous laisse deviner... Revert de tout le travail d'aujourd'hui :joie:
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#955 [POC] On remet tout le travail d'hier + tentative d'usage de pipe pour gérer le watermark à notre place
  api/lib/application/replication-data.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/replication-data_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#956 [TECH] Revert du travail d'aujourd'hui, TLDR on n'a pas trop avancé
  api/lib/application/replication-data.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#957 [TECH] On continue d'essayer un petit peu ce matin
  api/lib/application/replication-data.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/replication-data_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#958 Retour en arrière mais la faille est découverte et résolue
  api/lib/application/replication-data.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
Labels: :rocket: Ready to Merge

#959 [TECH] Exposer les traductions dans les données de réplication et résoudre les problèmes techniques
  api/lib/application/releases.js
  api/lib/application/replication-data.js
  api/lib/config.js
  api/lib/domain/models/Translation.js
  api/lib/domain/usecases/get-learning-content-for-replication.js
  api/lib/infrastructure/logger.js
  api/lib/infrastructure/repositories/translation-repository.js
  api/lib/infrastructure/utils/promise-streamer.js
  api/sample.env
  api/tests/acceptance/application/replication-data-controller_test.js
  api/tests/integration/infrastructure/repositories/translation-repository_test.js
  api/tests/tooling/database-builder/factory/build-mission.js
  api/tests/tooling/database-builder/factory/build-translation.js
  api/tests/unit/domain/models/Translation_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/skill-serializer_test.js
  api/tests/unit/infrastructure/utils/promise-streamer_test.js
Labels: :rocket: Ready to Merge

#954 [FEATURE] Gérer l'ajout d'espaces insécables en français/francophone sur les épreuves (PIX-17125)
  api/lib/application/challenges/index.js
  api/lib/domain/usecases/create-challenge.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/update-challenge.js
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/domain/usecases/create-challenge_test.js
  api/tests/unit/domain/usecases/update-challenge_test.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#961 [FEATURE] Transformer les espaces classiques en espaces fines insécables devant certains caractères spéciaux (PIX-17590)
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/domain/usecases/create-challenge_test.js
  api/tests/unit/domain/usecases/update-challenge_test.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#962 [FEATURE] Devant certains caractères spéciaux, ne pas remplacer le vide par une espace fine insécable (PIX-17603)
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
Labels: :rocket: Ready to Merge

#964 [TECH] Gérer le traitement du header conditionnel "if-modified-since" dans le endpoint GET /releases/latest pour ne renvoyer la dernière release que si elle est plus récente que la date transmise
  api/lib/application/releases.js
  api/lib/infrastructure/repositories/release-repository.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#963 [BUGFIX] Le traitement des URLs à ignorer ne marche pas bien lorsque les casses dans les URLs sont différentes (PIX-17398)
  api/lib/domain/models/WhitelistedUrl.js
  api/tests/unit/domain/models/WhitelistedUrl_test.js
Labels: :rocket: Ready to Merge, team-contenu

#965 [FEATURE] Ne pas tenir compte des URLs à ne pas analyser dans l'export des URLs externes (PIX-17260)
  api/lib/domain/usecases/export-external-urls-from-release.js
  api/lib/infrastructure/scheduled-jobs/export-external-url-list-job-processor.js
  api/tests/unit/domain/usecases/export-external-urls-from-release_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#966 [BUGFIX] Les parenthèses n'étaient pas bien prises en compte lors de l'identification des URLs dans les champs d'épreuve pour la moulinette et pour l'export des urls externes (PIX-15983)
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#967 [FEATURE] Vérifier la viablilité d'un lien ajouté à un tutoriel (PIX-17660)
  pix-editor/app/components/field/tutorials.hbs
  pix-editor/app/components/field/tutorials.js
  pix-editor/app/components/form/skill.js
  pix-editor/app/components/form/tutorial.hbs
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/tag.js
  pix-editor/mirage/factories/tutorial.js
  pix-editor/tests/acceptance/create-tutorial-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK
