Repository 1024pix/pix-editor, pull requests merged in 2025-06, with the labels that each got.

#1009 [FEATURE] ajout d'une tooltip + renommage d'un label (PIX-17954)
  pix-editor/app/components/field/toggle-field.hbs
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/field/toggle-field.scss
  pix-editor/app/templates/authenticated/competence/prototypes/localized.hbs
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/acceptance/modify-localized-challenge/modify-localized-challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1011 [FEATURE] Ajouter les métadonnées en bas du formulaire d'un proto en édition et consultation (PIX-17955)
  pix-editor/app/components/challenge-view/challenge-view.gjs
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/styles/components/challenge-view.scss
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/integration/components/challenge-view/challenge-view-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1010 [BUGFIX] Problème d'actualisation du label framework dans la sidebar (PIX-12884)
  pix-editor/app/components/sidebar/navigation.js
  pix-editor/tests/unit/component/sidebar/navigation-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1002 [TECH] Sortir les thématiques du proxy Airtable (PIX-17960)
  api/lib/application/airtable-proxy.js
  api/lib/application/thematics.js
  api/lib/application/types.js
  api/lib/domain/models/Thematic.js
  api/lib/domain/usecases/create-skill.js
  api/lib/domain/usecases/create-thematic.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/list-thematics.js
  api/lib/domain/usecases/update-thematic.js
  api/lib/infrastructure/datasources/airtable/datasource.js
  api/lib/infrastructure/datasources/airtable/skill-datasource.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/thematic-serializer.js
  api/lib/infrastructure/translations/thematic.js
  api/lib/routes.js
  api/scripts/migrate-thematics-translations-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller-thematic_test.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller_test.js
  api/tests/acceptance/application/skills/index_test.js
  api/tests/acceptance/application/thematics_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/scripts/migrate-thematics-translations-from-airtable_test.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-thematic-datasource-object.js
  api/tests/tooling/input-output-data-builder/factory/build-thematic.js
  api/tests/unit/domain/models/Thematic_test.js
  api/tests/unit/domain/usecases/create-skill_test.js
  api/tests/unit/domain/usecases/create-thematic_test.js
  api/tests/unit/domain/usecases/list-thematics_test.js
  api/tests/unit/domain/usecases/update-thematic_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/thematic-serializer_test.js
  pix-editor/app/adapters/theme.js
  pix-editor/app/serializers/theme.js
  pix-editor/mirage/config.js
  pix-editor/mirage/factories/theme.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1015 [BUGFIX] L'édition d'attachments sur une épreuve traduite ne fonctionne pas (PIX-18096)
  api/lib/application/attachments.js
  api/lib/domain/models/Attachment.js
  api/lib/domain/services/update-pix-api-release-cache.js
  api/lib/domain/usecases/create-attachment.js
  api/lib/domain/usecases/delete-attachment.js
  api/lib/domain/usecases/update-attachment.js
  api/lib/infrastructure/repositories/attachment-repository.js
  api/lib/infrastructure/serializers/jsonapi/attachment-serializer.js
  api/tests/acceptance/application/attachments_test.js
  api/tests/integration/domain/services/update-pix-api-release-cache_test.js
  api/tests/integration/infrastructure/repositories/attachment-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-attachment.js
  api/tests/tooling/domain-builder/factory/build-attachment.js
  api/tests/unit/domain/models/Attachment_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/attachment-serializer_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1019 [TECH] Supprime test flacky sur la modification d'épreuve.
  pix-editor/tests/helpers/wait-for-select-to-be-closed.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#1032 [BUGFIX] Correction de flaky sur test acceptance modify-challenge
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/helpers/wait-for-select-to-be-closed.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#1033 [TECH] Sortir les tutoriels du proxy (PIX-18099)
  api/db/seeds/data/tags.js
  api/db/seeds/data/tutorials.js
  api/db/seeds/seed.js
  api/lib/application/airtable-proxy.js
  api/lib/application/tutorials.js
  api/lib/domain/models/Tutorial.js
  api/lib/domain/models/index.js
  api/lib/domain/services/update-pix-api-release-cache.js
  api/lib/domain/usecases/create-tutorial.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/search-tutorials.js
  api/lib/domain/usecases/update-tutorial.js
  api/lib/infrastructure/datasources/airtable/tutorial-datasource.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/repositories/tag-repository.js
  api/lib/infrastructure/repositories/tutorial-repository.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/tutorial-serializer.js
  api/lib/routes.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller_test.js
  api/tests/acceptance/application/tutorials_test.js
  api/tests/integration/domain/services/update-pix-api-release-cache_test.js
  api/tests/tooling/airtable-builder/factory/build-tutorial.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-tutorial-datasource-object.js
  api/tests/unit/infrastructure/serializers/jsonapi/tutorial-serializer_test.js
  pix-editor/app/adapters/tutorial.js
  pix-editor/app/components/field/tutorials.js
  pix-editor/app/components/form/tutorial.js
  pix-editor/app/models/tutorial.js
  pix-editor/app/serializers/tutorial.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/create-tutorial-test.js
  pix-editor/tests/unit/component/field/tutorials-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1034 [TECH] Grouper les recherches de tags par id
  api/lib/application/tags.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/search-tags.js
  api/lib/infrastructure/repositories/tag-repository.js
  api/tests/acceptance/application/tags_test.js
  pix-editor/app/adapters/tag.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1035 [TECH] Suppression des routes du proxy Airtable
  api/lib/application/airtable-proxy.js
  api/lib/domain/usecases/index.js
  api/lib/domain/usecases/proxy-delete-request-to-airtable.js
  api/lib/domain/usecases/proxy-read-request-to-airtable.js
  api/lib/domain/usecases/proxy-write-request-to-airtable.js
  api/lib/infrastructure/repositories/release-repository.js
  api/lib/infrastructure/serializers/airtable-serializer.js
  api/lib/infrastructure/translations/area.js
  api/lib/infrastructure/translations/competence.js
  api/lib/infrastructure/translations/skill.js
  api/lib/infrastructure/translations/utils.js
  api/scripts/migrate-areas-translations-from-airtable/index.js
  api/scripts/migrate-attachments-translation-from-airtable/index.js
  api/scripts/migrate-challenges-translation-from-airtable/index.js
  api/scripts/migrate-competences-translation-from-airtable/index.js
  api/scripts/migrate-embed-title-translation-from-airtable/index.js
  api/scripts/migrate-skills-translation-from-airtable/index.js
  api/tests/acceptance/application/airtable-proxy/airtable-proxy-controller_test.js
  api/tests/scripts/migrate-areas-translations-from-airtable_test.js
  api/tests/scripts/migrate-attachments-translation-from-airtable_test.js
  api/tests/scripts/migrate-challenges-translation-from-airtable_test.js
  api/tests/scripts/migrate-competences-translation-from-airtable_test.js
  api/tests/scripts/migrate-embed-title-translation-from-airtable_test.js
  api/tests/scripts/migrate-skills-translation-from-airtable_test.js
  api/tests/unit/application/airtable-proxy_test.js
  api/tests/unit/domain/usecases/proxy-delete-request-to-airtable_test.js
  api/tests/unit/domain/usecases/proxy-read-request-to-airtable_test.js
  api/tests/unit/domain/usecases/proxy-write-request-to-airtable_test.js
  api/tests/unit/infrastructure/serializers/airtable-serializer_test.js
  api/tests/unit/infrastructure/translations/utils_test.js
  pix-editor/app/adapters/airtable.js
  pix-editor/app/adapters/note.js
  pix-editor/mirage/config.js
  pix-editor/tests/unit/adapters/airtable-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1031 [TECH] Suppression de dépréciations ember.
  pix-editor/app/app.js
  pix-editor/app/components/pop-in/challenge-log.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
  pix-editor/app/deprecation-workflow.js
  pix-editor/app/routes/authenticated/competence/prototypes/localized.js
  pix-editor/app/transforms/boolean.js
  pix-editor/mirage/config.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/integration/components/pop-in/challenge-log-test.js
  pix-editor/tests/unit/controllers/competence/skills/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1037 [BUGFIX] Le niveau du tuto n’est pas obligatoire (PIX-18193)
  api/lib/application/tutorials.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1040 [FEATURE] Modifier le terme "Type" en "Modalité" dans les formulaires et dans la vue atelier de l'atelier sur PixEditor (PIX-17961)
  pix-editor/app/components/challenge-view/challenge-view.gjs
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/components/list/workbench.js
  pix-editor/tests/integration/components/challenge-view/challenge-view-test.gjs
  pix-editor/tests/integration/components/form/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#1039 [BUGFIX] Corriger le déplacement d'un sujet (PIX-18209).
  api/lib/domain/models/Tube.js
  api/lib/domain/usecases/update-tube.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/tests/acceptance/application/tubes_test.js
  api/tests/unit/domain/models/Tube_test.js
  api/tests/unit/domain/usecases/update-tube_test.js
  pix-editor/app/controllers/authenticated/competence/tubes/single.js
  pix-editor/app/routes/authenticated/competence/tubes/single.js
  pix-editor/tests/unit/controllers/competence/tubes/single-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#974 [TECH] Refacto de la dropdown de recherche dans l'édition d'un acquis (PIX-17729)
  pix-editor/app/components/field/select-search.gjs
  pix-editor/app/components/field/tutorials.gjs
  pix-editor/app/components/field/tutorials.hbs
  pix-editor/app/components/field/tutorials.js
  pix-editor/app/components/form/skill.gjs
  pix-editor/app/components/pop-in/tutorial.gjs
  pix-editor/app/components/pop-in/tutorial.hbs
  pix-editor/app/components/pop-in/tutorial.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/field/select-search.scss
  pix-editor/app/styles/components/field/tutorials.scss
  pix-editor/tests/acceptance/create-tutorial-test.js
  pix-editor/tests/integration/components/field/select-search-test.gjs
  pix-editor/tests/integration/components/field/tutorials-test.js
  pix-editor/tests/unit/component/field/tutorials-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1047 [BUGFIX] Corriger l'affichage des drapeaux des tutoriels (PIX-18325)
  pix-editor/app/components/field/tutorials.gjs
  pix-editor/app/components/form/tutorial.js
  pix-editor/app/models/tutorial.js
  pix-editor/app/styles/components/field/tutorials.scss
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1049 [TECH] Ajout d'un script pour détecter les incohérences sur les attributs commun d'une même grappe d'épreuves (PIX-18358)
  api/lib/domain/models/Challenge.js
  api/scripts/scan-challenges-for-discrepancies-between-prototypes-and-alternatives.js
  api/tests/scripts/scan-challenges-for-discrepancies-between-prototypes-and-alternatives_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1052 [BUGFIX] La release ne fonctionne pas lorsqu'il existe un tube qui n'a pas d'acquis (PIX-18375)
  api/lib/infrastructure/datasources/airtable/tube-datasource.js
  api/tests/unit/infrastructure/datasources/airtable/tube-datasource_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1055 [TECH] Supprimer un test e2e trop instable
  pix-editor/tests/e2e/challenge.spec.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#1056 [BUGFIX] Problème visuel lorsque la V2 est choisit mais que la route n'existe pas (PIX-17282) 2e :)
  pix-editor/app/controllers/authenticated.js
  pix-editor/app/templates/authenticated.hbs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1063 [TECH] Migrer le composant de connexion vers gjs
  pix-editor/app/components/login-form.gjs
  pix-editor/app/components/login-form.hbs
  pix-editor/app/components/login-form.js
  pix-editor/tests/integration/components/login-form-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK

#1062 [TECH] Remplacement des dernières utilisations de `ember-power-select` (PIX-17726)
  pix-editor/app/components/field/select.hbs
  pix-editor/app/components/field/select.js
  pix-editor/app/components/pop-in/pdf-entries.gjs
  pix-editor/app/components/pop-in/pdf-entries.hbs
  pix-editor/app/components/pop-in/pdf-entries.js
  pix-editor/app/components/power-select/custom-trigger.hbs
  pix-editor/app/components/sidebar/main.hbs
  pix-editor/app/components/sidebar/navigation.gjs
  pix-editor/app/components/sidebar/navigation.hbs
  pix-editor/app/components/sidebar/navigation.js
  pix-editor/app/components/sidebar/search.gjs
  pix-editor/app/components/sidebar/search.hbs
  pix-editor/app/controllers/authenticated/target-profile.js
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/styles/_custom-basic-dropdown.scss
  pix-editor/app/styles/_custom-select.scss
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/styles/_skill.scss
  pix-editor/app/styles/_target-profile.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/pop-in/pdf-entries.scss
  pix-editor/app/styles/components/sidebar/navigation.scss
  pix-editor/app/styles/components/sidebar/search.scss
  pix-editor/app/templates/application.hbs
  pix-editor/app/templates/authenticated/target-profile.hbs
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/area-management/new-test.js
  pix-editor/tests/acceptance/competence-management/new-test.js
  pix-editor/tests/acceptance/create-framework-test.js
  pix-editor/tests/acceptance/navigate-through-frameworks-test.js
  pix-editor/tests/acceptance/search-test.js
  pix-editor/tests/integration/components/field/select-test.js
  pix-editor/tests/integration/components/pop-in/pdf-entries-test.gjs
  pix-editor/tests/integration/components/pop-in/pdf-entries-test.js
  pix-editor/tests/integration/components/power-select/custom-trigger-test.js
  pix-editor/tests/integration/components/sidebar/navigation-test.gjs
  pix-editor/tests/integration/components/sidebar/search-test.gjs
  pix-editor/tests/unit/component/sidebar/navigation-test.js
  pix-editor/tests/unit/controllers/target-profile-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1076 [BUGFIX] Fix sur la notation des couleurs rgba
  pix-editor/.stylelintrc.json
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/styles/_competence.scss
  pix-editor/app/styles/_custom-tabs.scss
  pix-editor/app/styles/_custom-tooltip.scss
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/_lists.scss
  pix-editor/app/styles/_sidebar.scss
  pix-editor/app/styles/_skill.scss
  pix-editor/app/styles/_target-profile.scss
  pix-editor/app/styles/components/card.scss
  pix-editor/app/styles/components/challenge-view-header.scss
  pix-editor/app/styles/components/challenges-production-header.scss
  pix-editor/app/styles/components/form/tutorial.scss
  pix-editor/app/styles/components/sidebar/navigation.scss
  pix-editor/app/styles/components/sidebar/search.scss
  pix-editor/app/styles/globals/table.scss
  pix-editor/package-lock.json
Labels: bug, Func Review OK, :rocket: Ready to Merge, Tech Review OK
