Repository 1024pix/pix-editor, pull requests merged in 2025-05, with the labels that each got.

#971 [BUGFIX] Moulinette URLS : URL entre parenthèses mal identifiée si un caractère succède immédiatement la dernière parenthèse (PIX-17725)
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#975 [FEATURE] Suppression automatique des feuilles de calcul vieilles de plus de 3 mois dans l'exports des URLs externes (PIX-17360)
  api/lib/infrastructure/repositories/url-repository.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#976 [TECH] Retirer les mots "whiteliste/whitelistée" des messages renvoyés par l'API pour parler des URLs à ne pas analyser (PIX-17462)
  api/lib/application/whitelisted-urls/index.js
  api/lib/domain/models/WhitelistedUrl.js
  api/tests/acceptance/application/whitelisted-urls/whitelisted-urls_test.js
  api/tests/unit/domain/models/WhitelistedUrl_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#973 [TECH] Suppression du dropdown pour PixSelect dans le header (PIX-17228)
  pix-editor/app/components/competence/competence-header.gjs
  pix-editor/app/components/competence/competence-header.hbs
  pix-editor/app/components/competence/competence-header.js
  pix-editor/app/components/form/note.gjs
  pix-editor/app/components/form/note.hbs
  pix-editor/app/components/form/note.js
  pix-editor/app/components/target-profile/navigation.hbs
  pix-editor/app/components/target-profile/navigation.js
  pix-editor/app/controllers/authenticated/competence.js
  pix-editor/app/controllers/authenticated/competence/prototypes/single.js
  pix-editor/app/controllers/authenticated/competence/skills/single.js
  pix-editor/app/styles/_challenges.scss
  pix-editor/app/styles/_competence.scss
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/_skill.scss
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/app/templates/authenticated/competence/skills/single.hbs
  pix-editor/app/templates/authenticated/target-profile.hbs
  pix-editor/package-lock.json
  pix-editor/tests/acceptance/validate-prototype-test.js
  pix-editor/tests/integration/components/competence/competence-header-test.gjs
  pix-editor/tests/integration/components/competence/competence-header-test.js
  pix-editor/tests/integration/components/form/note-test.gjs
  pix-editor/tests/integration/components/form/note-test.js
  pix-editor/tests/integration/components/target-profile/navigation-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#978 [FEATURE] Pouvoir voir clairement et proprement la liste des noms des acquis concernés dans le tableau des URLs à ne pas analyser (PIX-17354)
  pix-editor/app/components/whitelisted-urls/list.hbs
  pix-editor/app/components/whitelisted-urls/related-skill-cell.gjs
  pix-editor/tests/acceptance/whitelisted-urls/creation-test.js
  pix-editor/tests/acceptance/whitelisted-urls/edition-test.js
  pix-editor/tests/integration/components/whitelisted-urls/list-test.js
  pix-editor/tests/integration/components/whitelisted-urls/related-skill-cell-test.gjs
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#980 [FEATURE] Utiliser le numéro de version de déclinaison dans le header v2 de l'affichage d'une épreuve en production (PIX-17756)
  pix-editor/app/components/challenge-view/challenge-view-header.gjs
  pix-editor/tests/integration/components/challenge-view/challenge-view-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#979 [BUGFIX] Rediriger vers la V2 depuis `/challenge/{id}` (PIX-17244)
  pix-editor/app/routes/authenticated/challenge.js
  pix-editor/tests/unit/.gitkeep
  pix-editor/tests/unit/routes/challenge-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, Tech Review OK

#988 [BUGFIX] Échec de la création du workbench acquis lors de la création d’une compétence (PIX-17777)
  api/lib/domain/models/Skill.js
  api/lib/domain/models/Tube.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/models/Tube_test.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/app/controllers/authenticated/competence/skills/new.js
  pix-editor/app/models/skill.js
  pix-editor/app/models/tube.js
  pix-editor/app/routes/authenticated/competence/skills/new.js
  pix-editor/mirage/config.js
  pix-editor/tests/unit/controllers/competence-management/new-test.js
  pix-editor/tests/unit/models/tube-test.js
Labels: bug, Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#989 [TECH] Empêcher les tests flaky liés à l'affichage de plusieurs PixSelect
  pix-editor/tests/acceptance/competence/skills/single-test.js
  pix-editor/tests/acceptance/create-challenge-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/helpers/wait-for-select-to-be-closed.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#992 [BUGFIX] Un lien de tutoriel sans protocole casse la moulinette (PIX-17825)
  api/lib/domain/usecases/validate-urls-from-release.js
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/domain/usecases/validate-urls-from-release_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#984 [TECH] Déplacer la création de la thématique workbench dans l’API (PIX-17770)
  api/lib/application/competences/competences.js
  api/lib/domain/models/Thematic.js
  api/lib/domain/usecases/create-competence.js
  api/lib/infrastructure/datasources/airtable/thematic-datasource.js
  api/lib/infrastructure/repositories/thematic-repository.js
  api/lib/infrastructure/transformers/thematic-transformer.js
  api/lib/infrastructure/translations/thematic.js
  api/tests/acceptance/application/competences/competences_test.js
  api/tests/integration/infrastructure/repositories/thematic-repository_test.js
  api/tests/tooling/airtable-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/build-thematic.js
  api/tests/tooling/domain-builder/factory/datasource-objects/build-thematic-datasource-object.js
  api/tests/tooling/input-output-data-builder/factory/build-thematic.js
  api/tests/unit/domain/usecases/create-competence_test.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence-management/new-test.js
  pix-editor/tests/unit/controllers/competence-management/new-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#993 [FEATURE] Gérer l'ajout d'espace insécable mot, dit NBSP, dans du texte contenant des guillemets du style «» et deux-points : (PIX-17616)
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#994 [FEATURE] Gérer l'ajout d'espaces insécables dans les indices fr des acquis lors de la création et de la modification (PIX-17617)
  api/lib/application/skills/skills.js
  api/lib/domain/models/Skill.js
  api/lib/domain/usecases/create-skill.js
  api/lib/domain/usecases/update-skill.js
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/usecases/create-skill_test.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#997 [TECH] Ajouter des pièces jointes aux seeds
  api/db/seeds/data/attachments.js
  api/db/seeds/data/challenges.js
  api/lib/config.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#982 [TECH] Suppression de `ember-basic-dropdown` du composant `popin-select-location` (PIX-17793)
  pix-editor/app/components/form/select-location.gjs
  pix-editor/app/components/pop-in/select-location.gjs
  pix-editor/app/components/pop-in/select-location.hbs
  pix-editor/app/components/pop-in/select-location.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/select-location.scss
  pix-editor/app/templates/authenticated/competence/prototypes/single.hbs
  pix-editor/app/templates/authenticated/competence/skills/single.hbs
  pix-editor/app/templates/authenticated/competence/tubes/single.hbs
  pix-editor/tests/acceptance/competence/prototypes/single-test.js
  pix-editor/tests/acceptance/competence/skills/single-test.js
  pix-editor/tests/index.html
  pix-editor/tests/integration/components/pop-in/select-location-test.gjs
  pix-editor/tests/integration/components/pop-in/select-location-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#999 [BUMP] caniuse-lite
  pix-editor/package-lock.json
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, dependencies

#977 [TECH] Suppression du dropdown pour PixSelect dans les statuts d'un acquis (PIX-17235)
  pix-editor/app/components/form/skill.gjs
  pix-editor/app/components/form/skill.hbs
  pix-editor/app/components/form/skill.js
  pix-editor/app/styles/_skill.scss
  pix-editor/mirage/factories/skill.js
  pix-editor/tests/integration/components/form/skill-test.gjs
  pix-editor/tests/integration/components/form/skill-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#998 [TECH] Déplacer la création de l’acquis workbench dans l’API (PIX-17772) (PIX-17768)
  api/lib/domain/models/Skill.js
  api/lib/domain/usecases/create-competence.js
  api/lib/infrastructure/transformers/skill-transformer.js
  api/tests/acceptance/application/competences/competences_test.js
  api/tests/unit/domain/models/Skill_test.js
  api/tests/unit/domain/usecases/create-competence_test.js
  api/tests/unit/infrastructure/transformers/skill-transformer_test.js
  pix-editor/app/controllers/authenticated/competence-management/new.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/competence-management/new-test.js
  pix-editor/tests/unit/controllers/competence-management/new-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1001 [BUGFIX] Des espaces insécables s'ajoutent au niveau des « » même s'il y en a déjà. (PIX-17957)
  api/lib/infrastructure/utils/normalize-non-breaking-space.js
  api/tests/unit/infrastructure/utils/normalize-non-breaking-space_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#1007 [FEATURE] Ajout d'une route pour récupérer les noms de pays (PIX-17982)
  api/db/seeds/data/localized-challenges.js
  api/lib/application/countries.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/Country.js
  api/lib/domain/models/index.js
  api/lib/infrastructure/repositories/country-repository.js
  api/lib/infrastructure/repositories/index.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/country-serializer.js
  api/lib/infrastructure/serializers/jsonapi/index.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/routes.js
  api/scripts/migrate-localized-challenges-geography/index.js
  api/tests/acceptance/application/countries_test.js
  api/tests/integration/infrastructure/repositories/country-repository_test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech Review OK
