Repository 1024pix/pix-editor, pull requests merged in 2025-01, with the labels that each got.

#845 [FEATURE] Pouvoir voir la liste des épreuves d'un acquis lorsqu'on clique dessus depuis la vue V2 (PIX-15784)
  api/lib/application/skills/index.js
  api/lib/application/skills/skills.js
  api/lib/application/types.js
  api/lib/domain/readmodels/CompetenceOverview.js
  api/lib/domain/usecases/get-skill-challenges-production.js
  api/lib/domain/usecases/index.js
  api/tests/acceptance/application/competences/overviews_test.js
  api/tests/acceptance/application/skills/index_test.js
  api/tests/unit/domain/usecases/get-skill-challenges-production_test.js
  pix-editor/app/adapters/challenge.js
  pix-editor/app/components/competence-overview-skill.gjs
  pix-editor/app/components/competence-overview.gjs
  pix-editor/app/components/competence-overview/challenges-production-header.gjs
  pix-editor/app/components/competence-overview/challenges-production.gjs
  pix-editor/app/controllers/authenticated.js
  pix-editor/app/helpers/flag-for-language.js
  pix-editor/app/models/challenge.js
  pix-editor/app/models/skill.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/v2/competence-overview.js
  pix-editor/app/routes/authenticated/v2/competence-overview/challenges.js
  pix-editor/app/serializers/skill.js
  pix-editor/app/services/multipanel-manager.js
  pix-editor/app/styles/_global.scss
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/authenticated-v2.scss
  pix-editor/app/styles/components/challenges-production-header.scss
  pix-editor/app/styles/components/challenges-production.scss
  pix-editor/app/styles/components/competence-overview-skill.scss
  pix-editor/app/styles/components/competence-overview.scss
  pix-editor/app/templates/authenticated.hbs
  pix-editor/app/templates/authenticated/static-courses/list.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview/challenges.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview/loading.hbs
  pix-editor/mirage/config.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
  pix-editor/tests/integration/components/competence-overview/challenges-production-test.gjs
  pix-editor/tests/unit/helpers/flag-for-language_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#854 [FEATURE] Afficher la consigne du tableau `challenges-production` sur 2 lignes (PIX-16072)
  pix-editor/app/components/competence-overview/challenges-production.gjs
  pix-editor/app/components/loader.hbs
  pix-editor/app/services/multipanel-manager.js
  pix-editor/app/styles/components/challenges-production.scss
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#857 [TECH] Remplacer les PixTables par des PixTables condensés (PIX-16039)
  pix-editor/app/components/competence-overview/challenges-production.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#858 [TECH] Extraire l'en-tête de la nouvelle page parente "V2" dans une route parente dédiée (PIX-16119)
  pix-editor/app/components/challenges-production/challenges-production-header.gjs
  pix-editor/app/components/challenges-production/challenges-production.gjs
  pix-editor/app/components/competence-header.gjs
  pix-editor/app/components/competence-overview/competence-overview-skill.gjs
  pix-editor/app/components/competence-overview/competence-overview.gjs
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/competence/prototypes.js
  pix-editor/app/routes/authenticated/v2.js
  pix-editor/app/routes/authenticated/v2/competence-overview.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/competence-header.scss
  pix-editor/app/styles/components/competence-overview.scss
  pix-editor/app/templates/authenticated/v2.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview/challenges.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview/loading.hbs
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
  pix-editor/tests/acceptance/v2/navigation-v1-v2_test.js
  pix-editor/tests/integration/components/competence-overview-skill-test.gjs
  pix-editor/tests/integration/components/competence-overview/challenges-production-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#828 [TECH] Script de comparaison des schémas des tables des différents environnements Airtable
  .gitignore
  api/package.json
  api/scripts/compare-airtable-schemas/bases-to-compare.js
  api/scripts/compare-airtable-schemas/compare-schemas.js
  api/scripts/compare-airtable-schemas/fetch-schemas.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#861 [TECH] Supprimer l'historique des données de script de passage en focus des acquis (PIX-16149)
  api/db/migrations/20250117132855_drop-historic-focus-table.js
  api/db/migrations/20250117133225_drop-focus-phrase-table.js
  api/scripts/fix-obsolete-cloned-challenges/index.js
  api/scripts/upload-multi-locales-to-phrase/index.js
  api/tests/scripts/fix-obsolete-cloned-challenges_test.js
  api/tests/scripts/upload-multi-locales-to-phrase_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#862 [BUGFIX] Moulinette des URLs KO - Ne pas tenir compte de la casse pour le début des URLs (PIX-15760)
  api/lib/infrastructure/utils/url-utils.js
  api/tests/unit/infrastructure/utils/url-utils_test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#859 [FEATURE] Afficher le tableau des épreuves localisées en fonction de la langue choisie lorsqu'on clique sur un acquis de la grille (PIX-15785)
  api/lib/application/skills/index.js
  api/lib/application/skills/skills.js
  api/lib/domain/readmodels/LocalizedChallenge.js
  api/lib/domain/readmodels/index.js
  api/lib/domain/usecases/get-skill-localized-challenges-production.js
  api/lib/domain/usecases/index.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/tests/acceptance/application/skills/index_test.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/readmodels/LocalizedChallenge_test.js
  api/tests/unit/domain/usecases/get-skill-localized-challenges-production_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  pix-editor/app/components/challenges-production/localized-challenges-production.gjs
  pix-editor/app/components/competence-header.gjs
  pix-editor/app/components/competence-overview/competence-overview-skill.gjs
  pix-editor/app/components/competence-overview/competence-overview.gjs
  pix-editor/app/components/dropdown-menu.gjs
  pix-editor/app/models/localized-challenge.js
  pix-editor/app/models/skill.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/v2/competence-overview/challenges.js
  pix-editor/app/routes/authenticated/v2/competence-overview/localized-challenges.js
  pix-editor/app/serializers/skill.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/challenges-production.scss
  pix-editor/app/styles/components/competence-overview-skill.scss
  pix-editor/app/styles/components/dropdown-menu.scss
  pix-editor/app/templates/authenticated/v2/competence-overview/localized-challenges.hbs
  pix-editor/mirage/config.js
  pix-editor/package-lock.json
  pix-editor/package.json
  pix-editor/tests/acceptance/v2/competence-overview/navigation-primary-localized_test.js
  pix-editor/tests/integration/components/challenges-production/challenges-production-test.gjs
  pix-editor/tests/integration/components/challenges-production/localized-challenges-production-test.gjs
  pix-editor/tests/integration/components/competence-overview/competence-overview-skill-test.gjs
  pix-editor/tests/integration/components/dropdown-menu-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#863 [BUGFIX] Afficher les données qualités depuis un acquis (PIX-15771)
  pix-editor/app/routes/authenticated/competence/skills/single.js
Labels: bug, :rocket: Ready to Merge, team-contenu, Tech Review OK

#856 [FEATURE] Affiche un challenge primaire (PIX-14859)
  pix-editor/app/components/challenge-view/challenge-view-header.gjs
  pix-editor/app/components/challenge-view/challenge-view.gjs
  pix-editor/app/components/challenges-production/challenges-production-header.gjs
  pix-editor/app/components/challenges-production/challenges-production.gjs
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/competence/prototypes.js
  pix-editor/app/routes/authenticated/competence/prototypes/single.js
  pix-editor/app/routes/authenticated/v2/challenge.js
  pix-editor/app/routes/authenticated/v2/competence-overview.js
  pix-editor/app/routes/authenticated/v2/competence-overview/challenges.js
  pix-editor/app/services/multipanel-manager.js
  pix-editor/app/styles/app.scss
  pix-editor/app/styles/components/challenge-view-header.scss
  pix-editor/app/styles/components/challenge-view.scss
  pix-editor/app/styles/components/challenges-production-header.scss
  pix-editor/app/styles/components/challenges-production.scss
  pix-editor/app/templates/authenticated/v2/challenge.hbs
  pix-editor/app/templates/authenticated/v2/competence-overview/challenges.hbs
  pix-editor/tests/acceptance/v2/competence-overview/challenges-production_test.js
  pix-editor/tests/acceptance/v2/competence-overview/expand-collapse-close-multiplanels_test.js
  pix-editor/tests/acceptance/v2/competence-overview/navigation-primary-localized_test.js
  pix-editor/tests/integration/components/challenge-view/challenge-view-test.gjs
  pix-editor/tests/integration/components/challenges-production/challenges-production-test.gjs
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu

#866 [TECH] Ne plus avoir de test flacky (PIX-16288).
  pix-editor/tests/acceptance/validate-prototype-test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#865 [TECH] Ajout d'une route permettant de télécharger un snapshot mémoire.
  api/lib/application/heapdump.js
  api/lib/routes.js
Labels: Func Review OK, :rocket: Ready to Merge, team-captains, Tech Review OK

#867 [FEATURE] Permettre de récupérer les traductions Phrase depuis la V2 (PIX-14858)
  pix-editor/app/components/competence-overview/competence-overview.gjs
  pix-editor/app/styles/components/competence-overview.scss
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/synchronize_translations_test.js
  pix-editor/tests/acceptance/v2/competence-overview/fetch-translations_test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-contenu, Tech Review OK

#870 [TECH] Utiliser le pixId pour la route authenticated/skill (PIX-16321)
  pix-editor/app/components/sidebar/search.js
  pix-editor/app/router.js
  pix-editor/app/routes/authenticated/skill.js
  pix-editor/mirage/config.js
  pix-editor/tests/acceptance/search-test.js
Labels: :rocket: Ready to Merge, team-contenu, Tech Review OK

#869 [FEATURE] Ajout d'options dans le challenge pour Pix Junior
  api/db/migrations/20250128134613_add-has-embed-internal-validation-to-challenges.js
  api/db/migrations/20250128134614_add-no-validation-needed-to-challenges.js
  api/lib/domain/models/Challenge.js
  api/lib/domain/models/LocalizedChallenge.js
  api/lib/domain/models/release/ChallengeForRelease.js
  api/lib/infrastructure/repositories/challenge-repository.js
  api/lib/infrastructure/repositories/localized-challenge-repository.js
  api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js
  api/lib/infrastructure/serializers/jsonapi/localized-challenge-serializer.js
  api/lib/infrastructure/transformers/challenge-transformer.js
  api/tests/acceptance/application/challenges/challenges_test.js
  api/tests/acceptance/application/databases/replication-data-controller_test.js
  api/tests/acceptance/application/localized-challenges_test.js
  api/tests/acceptance/application/phrase_test.js
  api/tests/acceptance/application/releases/releases-controller_test.js
  api/tests/integration/infrastructure/repositories/challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/localized-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/release-repository_test.js
  api/tests/scripts/migrate-localized-challenges-geography_test.js
  api/tests/tooling/database-builder/factory/build-localized-challenge.js
  api/tests/tooling/domain-builder/factory/build-challenge-for-release.js
  api/tests/tooling/domain-builder/factory/build-localized-challenge.js
  api/tests/unit/domain/models/Challenge_test.js
  api/tests/unit/domain/models/LocalizedChallenge_test.js
  api/tests/unit/domain/usecases/import-translations_test.js
  api/tests/unit/infrastructure/repository/challenge-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/localized-challenge-serializer_test.js
  api/tests/unit/infrastructure/transformers/challenge-transformer_test.js
  pix-editor/app/components/form/challenge.hbs
  pix-editor/app/models/challenge.js
  pix-editor/app/models/localized-challenge.js
  pix-editor/mirage/factories/challenge.js
  pix-editor/tests/acceptance/create-challenge-test.js
  pix-editor/tests/acceptance/modify-challenge/modify-challenge-test.js
  pix-editor/tests/unit/models/challenge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Pix-Junior
